"""Posts: generated by ``devx_scaffold``, then extended (soft delete, publish, idempotency)."""

from datetime import datetime
from typing import Annotated, Literal

from django.http import HttpRequest
from ninja import Schema
from ninja_devx import ControllerOptions, LoggingHook, idempotent, post
from ninja_devx.crud import CRUDController, Instance, SoftDeleteMixin
from pydantic import Field

from blog.models import Post


class PostOut(Schema):
    id: int
    author_id: int
    title: str
    slug: str
    body: str
    status: Literal["draft", "published"]
    created: datetime
    deleted_at: datetime | None
    tags: list[int]

    @staticmethod
    def resolve_tags(obj: Post) -> list[int]:
        return [related.pk for related in obj.tags.all()]


class PostIn(Schema):
    title: Annotated[str, Field(max_length=200, min_length=1)]
    slug: Annotated[str, Field(max_length=50, min_length=1, pattern="^[-a-zA-Z0-9_]+$")]
    body: str = ""
    status: Literal["draft", "published"] = "draft"
    tags: list[int] = []


class PostController(SoftDeleteMixin[Post, PostOut], CRUDController[Post, PostOut, PostIn]):
    options = ControllerOptions(tags=["posts"], hooks=[LoggingHook()])
    owner_field = "author"
    search_fields = ("title", "slug", "body")
    filter_fields = {"author": ("exact",), "status": ("exact",), "created": ("gte", "lte")}
    ordering_fields = ("id", "created", "title")

    @post("/{pk}/publish", response=PostOut, decorators=[idempotent()])
    def publish(self, request: HttpRequest, post: Instance[Post]) -> Post:
        post.status = Post.Status.PUBLISHED
        post.save(update_fields=["status"])
        return post
