# Generated by Django 6.1.1 on 2026-09-13 14:42

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=100)),
                ("payload", models.JSONField(default=dict)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ("created",),
            },
        ),
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("description", models.CharField(blank=True, max_length=200)),
                ("events", models.JSONField(default=list)),
                (
                    "secret",
                    models.TextField(
                        help_text="Signing secret; encrypted when WEBHOOK_SECRET_KEYS is set."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("failing_since", models.DateTimeField(blank=True, null=True)),
                ("disabled_reason", models.CharField(blank=True, max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_endpoints",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_status_code", models.PositiveIntegerField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="ninja_devx_webhooks.outboxevent",
                    ),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="ninja_devx_webhooks.webhookendpoint",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "webhook deliveries",
                "ordering": ("id",),
                "indexes": [
                    models.Index(fields=["status", "next_attempt_at"], name="ndx_webhook_due")
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("event", "endpoint"), name="ndx_webhook_once")
                ],
            },
        ),
    ]
