# Generated by Django 6.1.1 on 2026-09-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ninja_devx_webhooks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboxevent",
            name="audience",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="webhookdelivery",
            name="lease_token",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="webhookendpoint",
            name="tenant_key",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
