"""The test API's own contract, generated by schemathesis from its OpenAPI schema."""

import pytest
import schemathesis
from django.contrib.auth.models import User
from hypothesis import HealthCheck, settings

from tests.urls import api


@pytest.fixture
def api_schema(ninja_contract, db):
    User.objects.create(username="contract")
    return ninja_contract(api)


schema = schemathesis.pytest.from_fixture("api_schema")


@schema.parametrize()
@settings(max_examples=10, suppress_health_check=list(HealthCheck), deadline=None)
def test_api_contract(case):
    case.call_and_validate()
