"""Generated source must keep document text inert and reject ambiguous symbols."""

import ast
import json
import shutil
import subprocess

import pytest
from hypothesis import given, settings
from hypothesis import strategies as st

from ninja_devx.codegen import generate_python, generate_typescript

TEXT = [
    'A"""B',
    "'\\\n\r\t",
    "*/\nglobalThis.pwn = true; //",
    "` ${globalThis.pwn = true}",
    "Héllo 日本語 😀",
    "\u2028\u2029",
    "\x00 end",
]


def document(text, *, path='/literal"`\\/{class}'):
    return {
        "openapi": "3.1.0",
        "info": {"title": text, "version": text},
        "paths": {
            path: {
                "get": {
                    "operationId": "class",
                    "summary": text,
                    "parameters": [
                        {
                            "in": "path",
                            "name": "class",
                            "required": True,
                            "schema": {"type": "string"},
                        }
                    ],
                    "responses": {
                        "200": {
                            "description": "ok",
                            "content": {"application/json": {"schema": {"type": "object"}}},
                        }
                    },
                }
            }
        },
        "components": {
            "schemas": {
                "Example": {
                    "type": "object",
                    "description": text,
                    "properties": {"value": {"type": "string", "default": text}},
                }
            }
        },
    }


@pytest.mark.parametrize("style", ["pydantic", "typeddict"])
@pytest.mark.parametrize("text", TEXT)
def test_python_literals_and_paths_remain_data(text, style):
    source = generate_python(document(text), style=style)
    tree = ast.parse(source)
    assert (
        ast.get_docstring(tree, clean=False)
        == f"Generated by ninja-devx from {text} {text}. Do not edit."
    )
    clients = [
        node for node in tree.body if isinstance(node, ast.ClassDef) and node.name == "ApiClient"
    ]
    operation = next(
        node
        for node in clients[0].body
        if isinstance(node, ast.FunctionDef) and node.name == "class_"
    )
    assert ast.get_docstring(operation, clean=False) == text
    assert "_path(class_)" in source
    if style == "pydantic":
        # Exercise Unicode and escaped defaults without executing any API request.
        namespace = {"__name__": "source_safety"}
        exec(compile(source, "<generated>", "exec"), namespace)
        assert namespace["Example"]().value == text


@given(st.text(max_size=100))
@settings(max_examples=30, deadline=None)
def test_python_arbitrary_summary_is_a_literal(text):
    source = generate_python(document(text))
    assert (
        ast.get_docstring(ast.parse(source), clean=False)
        == f"Generated by ninja-devx from {text} {text}. Do not edit."
    )


@pytest.mark.parametrize("generator", [generate_python, generate_typescript])
@pytest.mark.parametrize("name", ["1Broken", "Break; injected()", "ApiError", "Ærø"])
def test_component_names_fail_before_source_is_returned(generator, name):
    spec = document("safe")
    spec["components"]["schemas"] = {name: {"type": "string"}}
    with pytest.raises(ValueError, match="identifier"):
        generator(spec)


@pytest.mark.parametrize("generator", [generate_python, generate_typescript])
def test_normalized_operation_collisions_are_explicit(generator):
    spec = document("safe")
    op = next(iter(spec["paths"].values()))["get"]
    spec["paths"] = {
        "/one/{class}": {"get": {**op, "operationId": "a-b"}},
        "/two/{class}": {"get": {**op, "operationId": "a_b"}},
    }
    with pytest.raises(ValueError, match="collision"):
        generator(spec)


def test_python_model_field_collision_is_explicit():
    spec = document("safe")
    spec["components"]["schemas"]["Example"]["properties"] = {
        "a-b": {"type": "string"},
        "a_b": {"type": "string"},
    }
    with pytest.raises(ValueError, match="collision"):
        generate_python(spec)


def test_invalid_client_name_and_unknown_reference_are_explicit():
    with pytest.raises(ValueError, match="identifier"):
        generate_python(document("safe"), class_name="Client: pass")
    spec = document("safe")
    spec["components"]["schemas"]["Example"] = {"$ref": "#/components/schemas/A); injected()"}
    for generator in (generate_python, generate_typescript):
        with pytest.raises(ValueError, match="reference"):
            generator(spec)


def test_typescript_escapes_compile_and_fetch_the_literal_path(tmp_path):
    npx, node = shutil.which("npx"), shutil.which("node")
    if npx is None or node is None:
        pytest.skip("requires Node and TypeScript")
    static = '/literal"`\\/Héllo 日本語 😀/'
    spec = document("\n".join(TEXT), path=static + "{class}")
    path = tmp_path / "client.ts"
    path.write_text(generate_typescript(spec))
    compiled = subprocess.run(
        [
            npx,
            "-y",
            "-p",
            "typescript@5.9.3",
            "tsc",
            "--strict",
            "--target",
            "es2022",
            "--module",
            "commonjs",
            "--lib",
            "es2022,dom",
            "--skipLibCheck",
            str(path),
        ],
        capture_output=True,
        text=True,
        timeout=60,
        check=False,
    )
    assert compiled.returncode == 0, compiled.stdout + compiled.stderr
    script = tmp_path / "check.cjs"
    script.write_text(
        """const assert = require('node:assert/strict');
const {createClient} = require('./client.js');
let sent;
const client = createClient({baseUrl: 'https://example.test', fetch: async (url, init) => {
  sent = String(url);
  return new Response(JSON.stringify({ok: true}), {headers: {'content-type': 'application/json'}});
}});
(async () => {
  assert.deepEqual(await client.class_('id/suffix'), {ok: true});
  assert.equal(globalThis.pwn, undefined);
  assert.equal(sent, """
        + json.dumps("https://example.test" + static + "id%2Fsuffix")
        + """);
})().catch(error => { console.error(error); process.exitCode = 1; });
"""
    )
    ran = subprocess.run(
        [node, str(script)], capture_output=True, text=True, timeout=10, check=False
    )
    assert ran.returncode == 0, ran.stdout + ran.stderr
