"""Typed Python clients (``httpx``, sync and async) from an OpenAPI document.

Two model styles:

- ``"pydantic"`` (default): ``BaseModel`` classes with the schema's constraints as
  ``Field(...)`` (lengths, patterns, ranges), ``datetime``/``date``/``UUID`` formats,
  defaults, descriptions and aliases for names that aren't identifiers. Request bodies are
  validated before they are sent (``exclude_unset``, so partial updates stay partial) and
  responses are validated into models.
- ``"typeddict"``: ``TypedDict`` shapes with no runtime dependency beyond httpx.
"""

from __future__ import annotations

import ast
import keyword
import math
import re
from collections.abc import Mapping, Sequence
from types import MappingProxyType
from typing import Final, Literal, cast

from . import source as _source
from .openapi import (
    Operation,
    Parameter,
    Schema,
    named_multipart_bodies,
    read_operations,
    ref_name,
)
from .openapi import as_list as _list
from .openapi import as_mapping as _mapping
from .openapi import as_strings as _strings

__all__ = ["generate_python"]

_IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")

_UPLOAD_TYPE = """\
class UploadFile(NamedTuple):
    filename: str
    content: bytes
    content_type: str = "application/octet-stream"
"""

_COOKIE_RUNTIME = """\
def _cookie_header(values: Mapping[str, object]) -> str | None:
    parts = [f"{name}={value}" for name, value in values.items() if value is not None]
    return "; ".join(parts) or None
"""

_MULTIPART_RUNTIME = """\
def _multipart(body: object) -> tuple[dict[str, str], dict[str, tuple[str, bytes, str]]]:
    values = _multipart_values(body)
    fields: dict[str, str] = {}
    files: dict[str, tuple[str, bytes, str]] = {}
    for name, value in values.items():
        if value is None:
            continue
        if isinstance(value, UploadFile):
            files[name] = (value.filename, value.content, value.content_type)
        elif isinstance(value, bytes):
            files[name] = (name, value, "application/octet-stream")
        elif isinstance(value, str | int | float | bool):
            fields[name] = str(value).lower() if isinstance(value, bool) else str(value)
        else:
            raise TypeError(f"Unsupported multipart value for {name!r}")
    return fields, files
"""

_RUNTIME = """\
class ApiError(Exception):
    def __init__(
        self, status_code: int, body: object, headers: Mapping[str, str] | None = None
    ) -> None:
        super().__init__(f"Request failed with status {status_code}")
        self.status_code = status_code
        self.body = body
        self.headers = dict(headers or {})


_Primitive = str | int | float | bool | None


def _query(values: Mapping[str, object]) -> dict[str, _Primitive | list[_Primitive]]:
    return {
        key: cast("_Primitive | list[_Primitive]", value)
        for key, value in values.items()
        if value is not None
    }


def _path(value: object) -> str:
    return quote(str(value), safe="")


def _header_value(value: object) -> str:
    return str(value).lower() if isinstance(value, bool) else str(value)


def _headers(
    values: Mapping[str, object], extra: Mapping[str, str] | None, *, multipart: bool = False
) -> httpx.Headers:
    headers = httpx.Headers(extra)
    for name, value in values.items():
        if value is not None:
            headers[name] = (
                ",".join(_header_value(item) for item in value)
                if isinstance(value, list | tuple) else _header_value(value)
            )
    if multipart and "Content-Type" in headers:
        del headers["Content-Type"]
    return headers


def _decode(response: httpx.Response) -> object:
    media_type = response.headers.get("Content-Type", "").split(";", 1)[0].lower()
    body: object = None
    if response.content:
        if media_type == "application/json" or media_type.endswith("+json"):
            try:
                body = response.json()
            except ValueError:
                raise ApiError(response.status_code, response.text, response.headers) from None
        elif media_type.startswith("text/") or not response.is_success:
            body = response.text
        else:
            body = response.content
    if not response.is_success:
        raise ApiError(response.status_code, body, response.headers)
    return body
"""


def generate_python(
    document: Schema,
    *,
    class_name: str = "ApiClient",
    style: Literal["pydantic", "typeddict"] = "pydantic",
) -> str:
    document = named_multipart_bodies(document)
    _validate(document, class_name=class_name, style=style)
    if style == "pydantic":
        return _generate_pydantic(document, class_name=class_name)
    info = _mapping(document.get("info"))
    operations = read_operations(document)
    parts = [
        "# ruff: noqa: E501",
        _source.literal(
            f"Generated by ninja-devx from {info.get('title', 'API')} "
            f"{info.get('version', '')}. Do not edit."
        ),
        "",
        "from __future__ import annotations",
        "",
        _collections_import(operations),
        "from typing import Literal, NamedTuple, NotRequired, TypedDict, cast",
        "from urllib.parse import quote",
        "",
        "import httpx",
        "",
        '__all__ = ["ApiError", "UploadFile", "Async' + class_name + '", "' + class_name + '"]',
        "",
        "",
    ]
    parts.extend([_UPLOAD_TYPE, ""])
    schemas = _mapping(_mapping(document.get("components")).get("schemas"))
    for name, schema in schemas.items():
        parts.append(_declaration(name, _mapping(schema)))
        parts.append("")
    parts.append(_RUNTIME)
    parts.append(
        "def _multipart_values(body: object) -> Mapping[str, object]:\n"
        '    return cast("Mapping[str, object]", body or {})\n'
    )
    parts.append(_MULTIPART_RUNTIME)
    if _uses_cookies(operations):
        parts.append(_COOKIE_RUNTIME)
    parts.append(_client(class_name, operations, asynchronous=False))
    parts.append(_client(f"Async{class_name}", operations, asynchronous=True))
    source = "\n".join(parts)
    return _checked(source)


def _declaration(name: str, schema: Schema) -> str:
    properties = _mapping(schema.get("properties"))
    if not (schema.get("type") == "object" and properties):
        return f"{name} = {py_type(schema, quote_refs=False)}\n"
    required = set(_strings(schema.get("required")))
    items = [
        (
            key,
            py_type(_mapping(value))
            if key in required
            else f"NotRequired[{py_type(_mapping(value))}]",
        )
        for key, value in properties.items()
    ]
    if all(_IDENTIFIER.match(key) and not keyword.iskeyword(key) for key, _ in items):
        body = "\n".join(f"    {key}: {annotation}" for key, annotation in items)
        return f"class {name}(TypedDict):\n{body}\n"
    fields = ", ".join(
        f"{_source.literal(key)}: {_source.literal(annotation)}" for key, annotation in items
    )
    return f'{name} = TypedDict("{name}", {{{fields}}})\n'


def py_type(schema: Schema, *, quote_refs: bool = False) -> str:
    if schema.get("format") == "binary" and not schema.get("x-binary-response"):
        return "UploadFile | bytes"
    if schema.get("x-binary-response"):
        return "bytes"
    if "$ref" in schema:
        name = ref_name(str(schema["$ref"]))
        return f'"{name}"' if quote_refs else name
    for combinator in ("anyOf", "oneOf"):
        if combinator in schema:
            members = list(
                dict.fromkeys(
                    py_type(_mapping(item), quote_refs=quote_refs)
                    for item in _list(schema[combinator])
                )
            )
            return " | ".join(members)
    if "allOf" in schema:
        parts = _list(schema["allOf"])
        return (
            py_type(_mapping(parts[0]), quote_refs=quote_refs)
            if len(parts) == 1
            else "dict[str, object]"
        )
    if "enum" in schema:
        values = ", ".join(
            _source.literal(v) if isinstance(v, str) else repr(v) for v in _list(schema["enum"])
        )
        return f"Literal[{values}]"
    kind = schema.get("type")
    if kinds := _list(kind):
        return " | ".join(
            py_type({**schema, "type": item}, quote_refs=quote_refs) for item in kinds
        )
    simple = {
        "string": "str",
        "integer": "int",
        "number": "float",
        "boolean": "bool",
        "null": "None",
    }
    if isinstance(kind, str) and kind in simple:
        return simple[kind]
    if kind == "array":
        return f"list[{py_type(_mapping(schema.get('items')), quote_refs=quote_refs)}]"
    extra = schema.get("additionalProperties")
    if extra_schema := _mapping(extra):
        return f"dict[str, {py_type(extra_schema, quote_refs=quote_refs)}]"
    return "dict[str, object]" if kind == "object" else "object"


def _client(name: str, operations: list[Operation], *, asynchronous: bool) -> str:
    http = "httpx.AsyncClient" if asynchronous else "httpx.Client"
    lines = [
        f"class {name}:",
        f'    """{"Async client" if asynchronous else "Client"} for the API."""',
        "",
        "    def __init__(",
        "        self,",
        '        base_url: str = "",',
        "        *,",
        f"        client: {http} | None = None,",
        "        headers: Mapping[str, str] | None = None,",
        "    ) -> None:",
        f"        self._client = client or {http}(base_url=base_url, headers=headers)",
        "",
    ]
    if asynchronous:
        lines += [
            "    async def aclose(self) -> None:",
            "        await self._client.aclose()",
            "",
            f"    async def __aenter__(self) -> {name}:",
            "        return self",
            "",
            "    async def __aexit__(self, *exc_info: object) -> None:",
            "        await self.aclose()",
            "",
        ]
    else:
        lines += [
            "    def close(self) -> None:",
            "        self._client.close()",
            "",
            f"    def __enter__(self) -> {name}:",
            "        return self",
            "",
            "    def __exit__(self, *exc_info: object) -> None:",
            "        self.close()",
            "",
        ]
    for operation in operations:
        lines += _method(operation, asynchronous=asynchronous)
    return "\n".join(lines)


def _declared_headers(header_params: list[Parameter], cookie_params: list[Parameter]) -> str:
    entries = [f"{_source.literal(p.name)}: {_identifier(p.name)}" for p in header_params]
    if cookie_params:
        cookies = ", ".join(
            f"{_source.literal(p.name)}: {_identifier(p.name)}" for p in cookie_params
        )
        entries.append(f'"Cookie": _cookie_header({{{cookies}}})')
    return "{" + ", ".join(entries) + "}"


def _method(operation: Operation, *, asynchronous: bool) -> list[str]:
    if operation.streaming:
        return _stream_method(operation, asynchronous=asynchronous, pydantic=False)
    path_params = [p for p in operation.parameters if p.location == "path"]
    query_params = [p for p in operation.parameters if p.location == "query"]
    header_params = [p for p in operation.parameters if p.location == "header"]
    cookie_params = [p for p in operation.parameters if p.location == "cookie"]
    arguments = ["self"] + [f"{_identifier(p.name)}: {py_type(p.schema)}" for p in path_params]
    if operation.body is not None:
        default = "" if operation.body_required else " = None"
        body_type = py_type(operation.body) + ("" if operation.body_required else " | None")
        arguments.append(f"body: {body_type}{default}")
    keyword_only = [
        f"{_identifier(p.name)}: {py_type(p.schema)}" + ("" if p.required else " | None = None")
        for p in sorted(
            [*query_params, *header_params, *cookie_params], key=lambda p: not p.required
        )
    ]
    arguments.append("*")
    arguments.extend(keyword_only)
    arguments.extend(
        [
            "request_headers: Mapping[str, str] | None = None",
            "on_response: Callable[[httpx.Response], None] | None = None",
        ]
    )
    if operation.response is not None:
        result = py_type(operation.response)
    else:
        result = "object" if operation.has_body else "None"
    params = ", ".join(f"{_source.literal(p.name)}: {_identifier(p.name)}" for p in query_params)
    path_literal = _source.path_expression(
        operation.path, {p.name: _identifier(p.name) for p in path_params}
    )
    call_arguments = [f'"{operation.method}"', path_literal]
    if query_params:
        call_arguments.append(f"params=_query({{{params}}})")
    if operation.body is not None:
        if operation.body_media_type == "multipart/form-data":
            call_arguments.extend(["data=_form_data", "files=_form_files"])
        else:
            call_arguments.append("json=body")
    multipart = operation.body_media_type == "multipart/form-data"
    call_arguments.append(
        f"headers=_headers({_declared_headers(header_params, cookie_params)}, "
        f"request_headers, multipart={multipart})"
    )
    prefix = "async def" if asynchronous else "def"
    awaited = "await " if asynchronous else ""
    docstring = f"        {_source.literal(operation.summary)}" if operation.summary else None
    lines = _wrap(f"    {prefix} {_snake(operation.operation_id)}(", arguments, f") -> {result}:")
    if docstring:
        lines.append(docstring)
    if operation.body_media_type == "multipart/form-data":
        lines.append("        _form_data, _form_files = _multipart(body)")
    lines += _wrap(f"        response = {awaited}self._client.request(", call_arguments, ")")
    lines += ["        if on_response is not None:", "            on_response(response)"]
    if result == "None":
        lines.append("        _decode(response)")
    elif result == "object":
        lines.append("        return _decode(response)")
    else:
        lines.append(f'        return cast("{result}", _decode(response))')
    lines.append("")
    return lines


def _stream_method(operation: Operation, *, asynchronous: bool, pydantic: bool) -> list[str]:
    """A server-sent-events method yielding decoded lines from ``text/event-stream``."""
    type_fn = pydantic_type if pydantic else py_type
    path_params = [p for p in operation.parameters if p.location == "path"]
    query_params = [p for p in operation.parameters if p.location == "query"]
    header_params = [p for p in operation.parameters if p.location == "header"]
    cookie_params = [p for p in operation.parameters if p.location == "cookie"]
    arguments = ["self"] + [f"{_identifier(p.name)}: {type_fn(p.schema)}" for p in path_params]
    keyword_only = [
        f"{_identifier(p.name)}: {type_fn(p.schema)}" + ("" if p.required else " | None = None")
        for p in sorted(
            [*query_params, *header_params, *cookie_params], key=lambda p: not p.required
        )
    ]
    arguments.append("*")
    arguments.extend(keyword_only)
    arguments.append("request_headers: Mapping[str, str] | None = None")
    params = ", ".join(f"{_source.literal(p.name)}: {_identifier(p.name)}" for p in query_params)
    path_literal = _source.path_expression(
        operation.path, {p.name: _identifier(p.name) for p in path_params}
    )
    call_arguments = [f'"{operation.method}"', path_literal]
    if query_params:
        call_arguments.append(f"params=_query({{{params}}})")
    call_arguments.append(
        f"headers=_headers({_declared_headers(header_params, cookie_params)}, request_headers)"
    )
    prefix = "async def" if asynchronous else "def"
    result = "AsyncIterator[str]" if asynchronous else "Iterator[str]"
    lines = _wrap(f"    {prefix} {_snake(operation.operation_id)}(", arguments, f") -> {result}:")
    if operation.summary:
        lines.append(f"        {_source.literal(operation.summary)}")
    context = "async with" if asynchronous else "with"
    lines += _wrap(f"        {context} self._client.stream(", call_arguments, ") as response:")
    lines += [
        "            response.raise_for_status()",
        f"            {'async for' if asynchronous else 'for'} line in "
        f"response.{'aiter_lines' if asynchronous else 'iter_lines'}():",
        "                yield line",
        "",
    ]
    return lines


def _wrap(opening: str, items: list[str], closing: str) -> list[str]:
    """One line when it fits in 100 characters, else one item per line (ruff format style)."""
    line = f"{opening}{', '.join(items)}{closing}"
    if len(line) <= 100:
        return [line]
    indent = " " * (len(opening) - len(opening.lstrip()) + 4)
    return [opening, *(f"{indent}{item}," for item in items), f"{indent[:-4]}{closing}"]


def _snake(value: str) -> str:
    value = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", value)
    name = re.sub(r"[^0-9a-zA-Z]+", "_", value).strip("_").lower()
    if not name or name[0].isdigit():
        name = "operation_" + name
    return f"{name}_" if keyword.iskeyword(name) else name


def _collections_import(operations: Sequence[Operation]) -> str:
    names = ["Callable", "Mapping"]
    if any(operation.streaming for operation in operations):
        names = ["AsyncIterator", *names[:1], "Iterator", *names[1:]]
    return f"from collections.abc import {', '.join(names)}"


def _uses_cookies(operations: Sequence[Operation]) -> bool:
    return any(p.location == "cookie" for operation in operations for p in operation.parameters)


def _identifier(name: str) -> str:
    cleaned = re.sub(r"\W", "_", name)
    if not cleaned or cleaned[0].isdigit():
        cleaned = "parameter_" + cleaned
    reserved = {
        "self",
        "body",
        "query",
        "headers",
        "cookies",
        "files",
        "cast",
        "_path",
        "_query",
        "_jsonable",
        "_headers",
        "_header_value",
        "_cookie_header",
        "_multipart",
        "_multipart_values",
        "_form_data",
        "_form_files",
        "request_headers",
        "on_response",
    }
    return f"{cleaned}_" if keyword.iskeyword(cleaned) or cleaned in reserved else cleaned


# --- Pydantic style ---------------------------------------------------------------------

_FORMATS: Final = MappingProxyType(
    {
        "date-time": "_dt.datetime",
        "date": "_dt.date",
        "time": "_dt.time",
        "duration": "_dt.timedelta",
        "uuid": "_uuid.UUID",
    }
)
_CONSTRAINTS: Final = MappingProxyType(
    {
        "minLength": "min_length",
        "maxLength": "max_length",
        "pattern": "pattern",
        "minimum": "ge",
        "maximum": "le",
        "exclusiveMinimum": "gt",
        "exclusiveMaximum": "lt",
        "multipleOf": "multiple_of",
        "minItems": "min_length",
        "maxItems": "max_length",
    }
)
_RESERVED: Final = frozenset(
    {"copy", "dict", "json", "schema", "validate", "construct", "fields", "model_config"}
)

_PYDANTIC_RUNTIME = """\
class ApiError(Exception):
    def __init__(
        self, status_code: int, body: object, headers: Mapping[str, str] | None = None
    ) -> None:
        super().__init__(f"Request failed with status {status_code}")
        self.status_code = status_code
        self.body = body
        self.headers = dict(headers or {})


_Primitive = str | int | float | bool | None


def _query(values: Mapping[str, object]) -> dict[str, _Primitive | list[_Primitive]]:
    return {
        key: cast("_Primitive | list[_Primitive]", _jsonable(value))
        for key, value in values.items()
        if value is not None
    }


def _path(value: object) -> str:
    return quote(str(_jsonable(value)), safe="")


def _jsonable(value: object) -> object:
    if isinstance(value, _BaseModel):
        return value.model_dump(mode="json", by_alias=True, exclude_unset=True)
    if isinstance(value, list | tuple):
        return [_jsonable(item) for item in value]
    if isinstance(value, Mapping):
        return {str(key): _jsonable(item) for key, item in value.items()}
    return _to_jsonable_python(value)


def _header_value(value: object) -> str:
    value = _jsonable(value)
    return str(value).lower() if isinstance(value, bool) else str(value)


def _headers(
    values: Mapping[str, object], extra: Mapping[str, str] | None, *, multipart: bool = False
) -> httpx.Headers:
    headers = httpx.Headers(extra)
    for name, value in values.items():
        if value is not None:
            headers[name] = (
                ",".join(_header_value(item) for item in value)
                if isinstance(value, list | tuple) else _header_value(value)
            )
    if multipart and "Content-Type" in headers:
        del headers["Content-Type"]
    return headers


def _decode(response: httpx.Response) -> object:
    media_type = response.headers.get("Content-Type", "").split(";", 1)[0].lower()
    body: object = None
    if response.content:
        if media_type == "application/json" or media_type.endswith("+json"):
            try:
                body = response.json()
            except ValueError:
                raise ApiError(response.status_code, response.text, response.headers) from None
        elif media_type.startswith("text/") or not response.is_success:
            body = response.text
        else:
            body = response.content
    if not response.is_success:
        raise ApiError(response.status_code, body, response.headers)
    return body
"""


def _generate_pydantic(document: Schema, *, class_name: str) -> str:
    info = _mapping(document.get("info"))
    operations = read_operations(document)
    parts = [
        "# ruff: noqa: E501, N815",
        _source.literal(
            f"Generated by ninja-devx from {info.get('title', 'API')} "
            f"{info.get('version', '')}. Do not edit."
        ),
        "",
        "from __future__ import annotations",
        "",
        "import datetime as _dt",
        "import uuid as _uuid",
        _collections_import(operations),
        "from typing import Annotated, Literal, NamedTuple, cast",
        "from urllib.parse import quote",
        "",
        "import httpx",
        "from pydantic import BaseModel as _BaseModel",
        "from pydantic import ConfigDict as _ConfigDict",
        "from pydantic import Field as _Field",
        "from pydantic import TypeAdapter as _TypeAdapter",
        "from pydantic_core import to_jsonable_python as _to_jsonable_python",
        "",
        '__all__ = ["ApiError", "UploadFile", "Async' + class_name + '", "' + class_name + '"]',
        "",
        "",
    ]
    parts.extend([_UPLOAD_TYPE, ""])
    schemas = _mapping(_mapping(document.get("components")).get("schemas"))
    for name, schema in schemas.items():
        parts.append(_model(name, _mapping(schema)))
        parts.append("")
    parts.append(_PYDANTIC_RUNTIME)
    parts.append("""def _multipart_values(body: object) -> Mapping[str, object]:
    if isinstance(body, _BaseModel):
        return {
            info.alias or name: getattr(body, name)
            for name, info in type(body).model_fields.items()
            if name in body.model_fields_set
        }
    return cast("Mapping[str, object]", body or {})
""")
    parts.append(_MULTIPART_RUNTIME)
    if _uses_cookies(operations):
        parts.append(_COOKIE_RUNTIME)
    adapters: dict[str, str] = {}
    sync_client = _pydantic_client(class_name, operations, adapters, asynchronous=False)
    async_client = _pydantic_client(f"Async{class_name}", operations, adapters, asynchronous=True)
    for annotation, name in adapters.items():
        parts.append(f"{name}: _TypeAdapter[{annotation}] = _TypeAdapter({annotation})")
    parts += ["", "", sync_client, async_client]
    source = "\n".join(parts)
    return _checked(source)


def pydantic_type(schema: Schema) -> str:
    if schema.get("format") == "binary" and not schema.get("x-binary-response"):
        return "UploadFile | bytes"
    """The annotation for ``schema`` in the pydantic style (formats become real types)."""
    if schema.get("x-binary-response"):
        return "bytes"
    if "$ref" in schema:
        return ref_name(str(schema["$ref"]))
    for combinator in ("anyOf", "oneOf"):
        if combinator in schema:
            members = list(
                dict.fromkeys(pydantic_type(_mapping(item)) for item in _list(schema[combinator]))
            )
            union = " | ".join(members)
            discriminator = _mapping(schema.get("discriminator"))
            property_name = discriminator.get("propertyName")
            if isinstance(property_name, str) and len(members) > 1:
                return f"Annotated[{union}, _Field(discriminator={_source.literal(property_name)})]"
            return union
    if "allOf" in schema:
        parts = _list(schema["allOf"])
        return pydantic_type(_mapping(parts[0])) if len(parts) == 1 else "dict[str, object]"
    if "enum" in schema:
        values = ", ".join(
            _source.literal(v) if isinstance(v, str) else repr(v) for v in _list(schema["enum"])
        )
        return f"Literal[{values}]"
    kind = schema.get("type")
    if kinds := _list(kind):
        return " | ".join(pydantic_type({**schema, "type": item}) for item in kinds)
    if kind == "string" and isinstance(schema.get("format"), str):
        return _FORMATS.get(str(schema["format"]), "str")
    if kind == "array":
        return f"list[{pydantic_type(_mapping(schema.get('items')))}]"
    if kind == "object" and (extra := _mapping(schema.get("additionalProperties"))):
        return f"dict[str, {pydantic_type(extra)}]"
    return py_type(schema)


def _model(name: str, schema: Schema) -> str:
    properties = _mapping(schema.get("properties"))
    if not (schema.get("type") == "object" and properties):
        if schema.get("type") == "object" or not schema:
            return f"{name} = dict[str, object]\n"
        return f"{name} = {pydantic_type(schema)}\n"
    required = set(_strings(schema.get("required")))
    lines = [f"class {name}(_BaseModel):"]
    if description := str(schema.get("description", "")).strip():
        lines.append(f"    {_source.literal(description)}")
        lines.append("")
    lines.append("    model_config = _ConfigDict(populate_by_name=True)")
    lines.append("")
    for key, raw in properties.items():
        value = _mapping(raw)
        attribute = _field_name(key)
        annotation = pydantic_type(value)
        arguments = _field_arguments(value)
        if attribute != key:
            arguments.insert(0, f"alias={_source.literal(key)}")
        default = ""
        if key not in required:
            if "default" in value:
                default = f" = {_python_literal(value['default'])}"
            else:
                if "None" not in annotation.split(" | "):
                    annotation = f"{annotation} | None"
                default = " = None"
        if arguments:
            annotation = f"Annotated[{annotation}, _Field({', '.join(arguments)})]"
        lines.append(f"    {attribute}: {annotation}{default}")
    return "\n".join(lines) + "\n"


def _field_arguments(schema: Schema) -> list[str]:
    arguments: list[str] = []
    members = [_mapping(item) for item in _list(schema.get("anyOf"))]
    non_null = [member for member in members if member.get("type") != "null"]
    if len(members) == 2 and len(non_null) == 1:  # ``T | None``: constraints live on ``T``
        schema = {**non_null[0], **{k: v for k, v in schema.items() if k != "anyOf"}}
    for keyword_name, argument in _CONSTRAINTS.items():
        value = schema.get(keyword_name)
        if isinstance(value, bool):
            continue
        if isinstance(value, int | float | str):
            arguments.append(f"{argument}={_python_literal(value)}")
    if description := str(schema.get("description", "")).strip():
        arguments.append(f"description={_source.literal(description)}")
    return arguments


def _field_name(key: str) -> str:
    name = re.sub(r"\W", "_", key)
    if not name or name[0].isdigit():
        name = f"field_{name}"
    if keyword.iskeyword(name) or name in _RESERVED or name.startswith(("model_", "_")):
        name = f"{name.lstrip('_')}_"
    return name


def _python_literal(value: object) -> str:
    if isinstance(value, str):
        return _source.literal(value)
    if isinstance(value, float) and not math.isfinite(value):
        raise ValueError("Non-finite defaults cannot be generated")
    if isinstance(value, bool) or value is None or isinstance(value, int | float):
        return repr(value)
    if isinstance(value, list | tuple):
        items: list[object] = list(cast("Sequence[object]", value))
        return "[" + ", ".join(_python_literal(item) for item in items) + "]"
    if isinstance(value, Mapping):
        entries = cast("Mapping[object, object]", value)
        return (
            "{"
            + ", ".join(
                f"{_source.literal(str(k))}: {_python_literal(v)}" for k, v in entries.items()
            )
            + "}"
        )
    raise ValueError(f"Unsupported default value type: {type(value).__name__}")


def _pydantic_client(
    name: str, operations: list[Operation], adapters: dict[str, str], *, asynchronous: bool
) -> str:
    lines = _client(name, [], asynchronous=asynchronous).split("\n")
    for operation in operations:
        lines += _pydantic_method(operation, adapters, asynchronous=asynchronous)
    return "\n".join(lines)


def _pydantic_method(
    operation: Operation, adapters: dict[str, str], *, asynchronous: bool
) -> list[str]:
    if operation.streaming:
        return _stream_method(operation, asynchronous=asynchronous, pydantic=True)
    path_params = [p for p in operation.parameters if p.location == "path"]
    query_params = [p for p in operation.parameters if p.location == "query"]
    header_params = [p for p in operation.parameters if p.location == "header"]
    cookie_params = [p for p in operation.parameters if p.location == "cookie"]
    arguments = ["self"] + [
        f"{_identifier(p.name)}: {pydantic_type(p.schema)}" for p in path_params
    ]
    if operation.body is not None:
        default = "" if operation.body_required else " = None"
        body_type = pydantic_type(operation.body) + ("" if operation.body_required else " | None")
        arguments.append(f"body: {body_type}{default}")
    keyword_only = [
        f"{_identifier(p.name)}: {pydantic_type(p.schema)}"
        + ("" if p.required else " | None = None")
        for p in sorted(
            [*query_params, *header_params, *cookie_params], key=lambda p: not p.required
        )
    ]
    arguments.append("*")
    arguments.extend(keyword_only)
    arguments.extend(
        [
            "request_headers: Mapping[str, str] | None = None",
            "on_response: Callable[[httpx.Response], None] | None = None",
        ]
    )
    if operation.response is not None:
        result = pydantic_type(operation.response)
    else:
        result = "object" if operation.has_body else "None"
    params = ", ".join(f"{_source.literal(p.name)}: {_identifier(p.name)}" for p in query_params)
    path_literal = _source.path_expression(
        operation.path, {p.name: _identifier(p.name) for p in path_params}
    )
    call_arguments = [f'"{operation.method}"', path_literal]
    if query_params:
        call_arguments.append(f"params=_query({{{params}}})")
    if operation.body is not None:
        if operation.body_media_type == "multipart/form-data":
            call_arguments.extend(["data=_form_data", "files=_form_files"])
        else:
            call_arguments.append("json=_jsonable(body)")
    multipart = operation.body_media_type == "multipart/form-data"
    call_arguments.append(
        f"headers=_headers({_declared_headers(header_params, cookie_params)}, "
        f"request_headers, multipart={multipart})"
    )
    prefix = "async def" if asynchronous else "def"
    awaited = "await " if asynchronous else ""
    lines = _wrap(f"    {prefix} {_snake(operation.operation_id)}(", arguments, f") -> {result}:")
    if operation.summary:
        lines.append(f"        {_source.literal(operation.summary)}")
    if operation.body_media_type == "multipart/form-data":
        lines.append("        _form_data, _form_files = _multipart(body)")
    lines += _wrap(f"        response = {awaited}self._client.request(", call_arguments, ")")
    lines += ["        if on_response is not None:", "            on_response(response)"]
    if result == "None":
        lines.append("        _decode(response)")
    elif result == "object":
        lines.append("        return _decode(response)")
    else:
        decoded = "_decode(response)"
        if len(operation.response_variants) > 1:
            lines.append("        decoded = _decode(response)")
            decoded = "decoded"
            for variant in operation.response_variants:
                if not variant.status.isdigit():
                    continue
                annotation = pydantic_type(variant.schema)
                adapter = adapters.setdefault(annotation, f"_RESULT_{len(adapters)}")
                condition = f"response.status_code == {int(variant.status)}"
                if variant.media_type is not None:
                    condition += (
                        ' and response.headers.get("Content-Type", "").split(";", 1)[0].lower() == '
                        + _source.literal(variant.media_type)
                    )
                lines.append(f"        if {condition}:")
                lines.append(f"            return {adapter}.validate_python(decoded)")
        adapter = adapters.setdefault(result, f"_RESULT_{len(adapters)}")
        lines.append(f"        return {adapter}.validate_python({decoded})")
    lines.append("")
    return lines


def _checked(source: str) -> str:
    source = re.sub(r"\n{3,}", "\n\n\n", source).rstrip() + "\n"
    ast.parse(source, filename="<generated Python client>")
    return source


def _validate(document: Schema, *, class_name: str, style: str) -> None:
    if style not in {"pydantic", "typeddict"}:
        raise ValueError(f"Unsupported Python model style: {style!r}")
    runtime = {
        "ApiError",
        "Mapping",
        "Literal",
        "TypedDict",
        "NotRequired",
        "Annotated",
        "cast",
        "httpx",
        "quote",
        "str",
        "int",
        "float",
        "bool",
        "list",
        "dict",
        "object",
        "Iterator",
        "AsyncIterator",
        "_BaseModel",
        "_TypeAdapter",
        "UploadFile",
        "NamedTuple",
        "_Field",
        "_ConfigDict",
        "_dt",
        "_uuid",
    }
    _source.identifier(class_name, reserved=runtime)
    _source.identifier("Async" + class_name, reserved=runtime)
    _source.schemas(document, reserved={*runtime, class_name, "Async" + class_name})
    operations = read_operations(document)
    _source.unique(
        (_snake(op.operation_id) for op in operations),
        namespace="client methods",
        reserved={
            "__init__",
            "__enter__",
            "__exit__",
            "__aenter__",
            "__aexit__",
            "close",
            "aclose",
            "_client",
        },
    )
    for op in operations:
        _source.unique(
            (
                _identifier(p.name)
                for p in op.parameters
                if p.location in {"path", "query", "header"}
            ),
            namespace=op.operation_id,
        )
    if style == "pydantic":
        for name, raw in _mapping(_mapping(document.get("components")).get("schemas")).items():
            properties = _mapping(_mapping(raw).get("properties"))
            _source.unique((_field_name(key) for key in properties), namespace=name)
