"""TypeScript types and a ``fetch`` client from an OpenAPI document."""

from __future__ import annotations

import json
import re

from . import source as _source
from .openapi import Operation, Parameter, Schema, named_multipart_bodies, read_operations, ref_name
from .openapi import as_list as _list
from .openapi import as_mapping as _mapping
from .openapi import as_strings as _strings

__all__ = ["generate_typescript"]

_IDENTIFIER = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")

_COOKIE_RUNTIME = """\
function cookieHeader(values: Record<string, unknown>): string | undefined {
  const parts = Object.entries(values)
    .filter(([, value]) => value != null)
    .map(([key, value]) => `${key}=${String(value)}`);
  return parts.length ? parts.join("; ") : undefined;
}
"""

_RUNTIME = """\
export class ApiError extends Error {
  constructor(
    readonly status: number,
    readonly body: unknown,
    readonly headers?: Headers,
  ) {
    super(`Request failed with status ${status}`);
  }
}

export interface ClientOptions {
  baseUrl?: string;
  headers?: Record<string, string> | (() => Record<string, string>);
  fetch?: typeof fetch;
}

export interface RequestOptions {
  headers?: Record<string, string>;
  onResponse?: (response: Response) => void;
}

function multipart(body: object | undefined): FormData | undefined {
  if (body === undefined) return undefined;
  const form = new FormData();
  for (const [key, value] of Object.entries(body)) {
    if (value == null) continue;
    if (value instanceof Blob) form.append(key, value);
    else if (["string", "number", "boolean"].includes(typeof value)) {
      form.append(key, String(value));
    }
    else throw new TypeError(`Unsupported multipart value for ${key}`);
  }
  return form;
}

type QueryValue = string | number | boolean | null | undefined | Array<string | number | boolean>;

function buildUrl(baseUrl: string, path: string, query?: Record<string, QueryValue>): string {
  const search = new URLSearchParams();
  for (const [key, value] of Object.entries(query ?? {})) {
    if (value === null || value === undefined) continue;
    for (const item of Array.isArray(value) ? value : [value]) search.append(key, String(item));
  }
  const suffix = search.toString();
  return `${baseUrl.replace(/\\/$/, "")}${path}${suffix ? `?${suffix}` : ""}`;
}
"""


def generate_typescript(document: Schema) -> str:
    document = named_multipart_bodies(document)
    reserved = {
        "ApiError",
        "ClientOptions",
        "RequestOptions",
        "QueryValue",
        "ApiClient",
        "Array",
        "Record",
        "Promise",
        "Error",
        "Blob",
        "FormData",
        "createClient",
        "buildUrl",
        "multipart",
        "cookieHeader",
        *_keywords(),
    }
    _source.schemas(document, reserved=reserved, javascript=True)
    operations = read_operations(document)
    for operation in operations:
        if operation.streaming:
            raise ValueError(
                f"{operation.operation_id}: streaming responses are unsupported in the "
                "TypeScript client; use the Python client for text/event-stream"
            )
    _source.unique(
        (_camel(op.operation_id) for op in operations),
        namespace="client methods",
        reserved={"then", "__proto__"},
    )
    for op in operations:
        _source.unique(
            (_identifier(p.name) for p in op.parameters if p.location == "path"),
            namespace=op.operation_id,
            reserved={"body", "query", "headers", "requestOptions"},
        )
    info = _mapping(document.get("info"))
    lines = [
        "// "
        + _source.literal(
            f"Generated by ninja-devx from {info.get('title', 'API')} "
            f"{info.get('version', '')}. Do not edit."
        ),
        "",
    ]
    schemas = _mapping(_mapping(document.get("components")).get("schemas"))
    for name, schema in schemas.items():
        lines.append(_declaration(name, _mapping(schema)))
        lines.append("")
    lines.append(_RUNTIME)
    if any(p.location == "cookie" for op in operations for p in op.parameters):
        lines.append(_COOKIE_RUNTIME)
    lines.append(_client(operations))
    return "\n".join(lines).rstrip() + "\n"


def _declaration(name: str, schema: Schema) -> str:
    properties = _mapping(schema.get("properties"))
    if schema.get("type") == "object" and properties:
        required = set(_strings(schema.get("required")))
        body = "\n".join(
            f"  {_key(key)}{'' if key in required else '?'}: {ts_type(_mapping(value))};"
            for key, value in properties.items()
        )
        return f"export interface {name} {{\n{body}\n}}"
    return f"export type {name} = {ts_type(schema)};"


def ts_type(schema: Schema) -> str:
    if schema.get("format") == "binary" and not schema.get("x-binary-response"):
        return "Blob"
    if schema.get("x-empty-response"):
        return "undefined"
    if schema.get("x-binary-response"):
        return "Uint8Array"
    if "$ref" in schema:
        return ref_name(str(schema["$ref"]))
    for combinator, separator in (("anyOf", " | "), ("oneOf", " | "), ("allOf", " & ")):
        if combinator in schema:
            members = list(
                dict.fromkeys(ts_type(_mapping(item)) for item in _list(schema[combinator]))
            )
            return separator.join(members) if len(members) > 1 else members[0]
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in _list(schema["enum"]))
    if "const" in schema:
        return json.dumps(schema["const"])
    kind = schema.get("type")
    if kinds := _list(kind):
        return " | ".join(ts_type({**schema, "type": item}) for item in kinds)
    if kind == "string":
        return "string"
    if kind in ("integer", "number"):
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "array":
        return f"Array<{ts_type(_mapping(schema.get('items')))}>"
    if kind == "object" or "properties" in schema:
        properties = _mapping(schema.get("properties"))
        if properties:
            required = set(_strings(schema.get("required")))
            fields = "; ".join(
                f"{_key(key)}{'' if key in required else '?'}: {ts_type(_mapping(value))}"
                for key, value in properties.items()
            )
            return f"{{ {fields} }}"
        extra = schema.get("additionalProperties")
        value = ts_type(extra_schema) if (extra_schema := _mapping(extra)) else "unknown"
        return f"Record<string, {value}>"
    return "unknown"


def _client(operations: list[Operation]) -> str:
    methods = [_method(operation) for operation in operations]
    body = ",\n".join(methods)
    return (
        "export function createClient(options: ClientOptions = {}) {\n"
        '  const baseUrl = options.baseUrl ?? "";\n'
        "  const fetchImpl = options.fetch ?? fetch;\n"
        "  async function request<T>(\n"
        "    method: string,\n"
        "    path: string,\n"
        "    query?: Record<string, QueryValue>,\n"
        "    body?: unknown,\n"
        "    declaredHeaders?: Record<string, unknown>,\n"
        "    requestOptions: RequestOptions = {},\n"
        "  ): Promise<T> {\n"
        '    const headers = new Headers({ Accept: "application/json" });\n'
        "    const extra =\n"
        '      typeof options.headers === "function" ? options.headers() : options.headers;\n'
        "    for (const [key, value] of Object.entries({...extra, ...requestOptions.headers})) {\n"
        "      headers.set(key, value);\n"
        "    }\n"
        "    for (const [key, value] of Object.entries(declaredHeaders ?? {})) {\n"
        "      if (value != null) {\n"
        "        headers.set(key, Array.isArray(value) ? value.join(',') : String(value));\n"
        "      }\n"
        "    }\n"
        '    if (body instanceof FormData) headers.delete("Content-Type");\n'
        '    else if (body !== undefined) headers.set("Content-Type", "application/json");\n'
        "    const response = await fetchImpl(buildUrl(baseUrl, path, query), {\n"
        "      method,\n"
        "      headers,\n"
        "      body: body instanceof FormData ? body :\n"
        "        body === undefined ? undefined : JSON.stringify(body),\n"
        "    });\n"
        "    requestOptions.onResponse?.(response);\n"
        "    const mediaType =\n"
        "      (response.headers.get('Content-Type') ?? '').split(';')[0].toLowerCase();\n"
        "    const raw = await response.arrayBuffer();\n"
        "    let data: unknown;\n"
        "    if (raw.byteLength) {\n"
        "      if (mediaType === 'application/json' || mediaType.endsWith('+json')) {\n"
        "        const text = new TextDecoder().decode(raw);\n"
        "        try { data = JSON.parse(text); } catch {\n"
        "          throw new ApiError(response.status, text, response.headers);\n"
        "        }\n"
        "      } else if (mediaType.startsWith('text/') || !response.ok) {\n"
        "        data = new TextDecoder().decode(raw);\n"
        "      } else { data = new Uint8Array(raw); }\n"
        "    }\n"
        "    if (!response.ok) throw new ApiError(response.status, data, response.headers);\n"
        "    return data as T;\n"
        "  }\n\n"
        f"  return {{\n{body},\n  }};\n"
        "}\n\n"
        "export type ApiClient = ReturnType<typeof createClient>;\n"
    )


def _method(operation: Operation) -> str:
    path_params = [p for p in operation.parameters if p.location == "path"]
    query_params = [p for p in operation.parameters if p.location == "query"]
    header_params = [p for p in operation.parameters if p.location == "header"]
    cookie_params = [p for p in operation.parameters if p.location == "cookie"]
    arguments = [f"{_identifier(p.name)}: {ts_type(p.schema)}" for p in path_params]
    if operation.body is not None:
        optional = "" if operation.body_required else " | undefined = undefined"
        arguments.append(f"body: {ts_type(operation.body)}{optional}")
    if query_params:
        fields = "; ".join(
            f"{_key(p.name)}{'' if p.required else '?'}: {_query_type(p)}" for p in query_params
        )
        default = "" if any(p.required for p in query_params) else " = {}"
        arguments.append(f"query: {{ {fields} }}{default}")
    if header_params:
        fields = "; ".join(
            f"{_key(p.name)}{'' if p.required else '?'}: {ts_type(p.schema)}" for p in header_params
        )
        default = "" if any(p.required for p in header_params) else " = {}"
        arguments.append(f"headers: {{ {fields} }}{default}")
    if cookie_params:
        fields = "; ".join(
            f"{_key(p.name)}{'' if p.required else '?'}: {ts_type(p.schema)}" for p in cookie_params
        )
        default = "" if any(p.required for p in cookie_params) else " = {}"
        arguments.append(f"cookies: {{ {fields} }}{default}")
    arguments.append("requestOptions: RequestOptions = {}")
    if operation.response is not None:
        result = ts_type(operation.response)
    else:
        result = "unknown" if operation.has_body else "void"
    path = _source.path_expression(
        operation.path, {p.name: _identifier(p.name) for p in path_params}, javascript=True
    )
    query = "query" if query_params else "undefined"
    body = "body" if operation.body is not None else "undefined"
    if operation.body_media_type == "multipart/form-data":
        body = f"multipart({body})"
    entries: list[str] = []
    if header_params:
        entries.append("...headers")
    if cookie_params:
        entries.append("Cookie: cookieHeader(cookies)")
    headers = "{ " + ", ".join(entries) + " }" if entries else "undefined"
    summary = f"    // {_source.literal(operation.summary)}\n" if operation.summary else ""
    return (
        f"{summary}    {_camel(operation.operation_id)}: ({', '.join(arguments)}) =>\n"
        f'      request<{result}>("{operation.method}", {path}, {query}, {body}, '
        f"{headers}, requestOptions)"
    )


def _query_type(parameter: Parameter) -> str:
    return ts_type(parameter.schema)


def _camel(value: str) -> str:
    head, *rest = re.split(r"[^0-9a-zA-Z]+", value)
    return _identifier(
        head[:1].lower() + head[1:] + "".join(part[:1].upper() + part[1:] for part in rest)
    )


def _identifier(name: str) -> str:
    name = re.sub(r"[^A-Za-z0-9_$]", "_", name)
    if not name or name[0].isdigit():
        name = "parameter_" + name
    return name + "_" if name in _keywords() else name


def _keywords() -> frozenset[str]:
    return frozenset(
        [
            "break",
            "case",
            "catch",
            "class",
            "const",
            "continue",
            "debugger",
            "default",
            "delete",
            "do",
            "else",
            "enum",
            "export",
            "extends",
            "false",
            "finally",
            "for",
            "function",
            "if",
            "import",
            "in",
            "instanceof",
            "new",
            "null",
            "return",
            "super",
            "switch",
            "this",
            "throw",
            "true",
            "try",
            "typeof",
            "var",
            "void",
            "while",
            "with",
            "as",
            "implements",
            "interface",
            "let",
            "package",
            "private",
            "protected",
            "public",
            "static",
            "yield",
            "any",
            "boolean",
            "constructor",
            "declare",
            "get",
            "module",
            "require",
            "number",
            "set",
            "string",
            "symbol",
            "type",
            "from",
            "of",
            "await",
            "async",
            "undefined",
            "unknown",
            "never",
        ]
    )


def _key(name: str) -> str:
    return name if _IDENTIFIER.match(name) else json.dumps(name)
