# Generated by Django 6.1.1 on 2026-09-13 15:23

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                ("key", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("token", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("fingerprint", models.CharField(max_length=64)),
                ("state", models.CharField(default="running", max_length=12)),
                ("status", models.PositiveSmallIntegerField(null=True)),
                ("content", models.BinaryField(default=bytes)),
                ("headers", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True, null=True)),
            ],
            options={
                "verbose_name": "idempotency record",
            },
        ),
    ]
