# Generated by Django 6.1.1 on 2026-09-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ninja_devx", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key_digest", models.CharField(max_length=64, unique=True)),
                ("key", models.TextField()),
                ("namespace", models.CharField(db_index=True, max_length=64)),
                ("owner_scope", models.CharField(max_length=64)),
                ("expected_size", models.PositiveBigIntegerField()),
                ("content_type", models.CharField(max_length=255)),
                ("checksum_sha256", models.CharField(blank=True, max_length=44)),
                ("version_id", models.TextField(blank=True)),
                ("etag", models.TextField(blank=True)),
                ("state", models.CharField(default="pending", max_length=16)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("completed_at", models.DateTimeField(null=True)),
                ("cleaned_at", models.DateTimeField(null=True)),
            ],
        ),
    ]
