"""Generate the sync twin of async code, and check that it has not drifted.

Write the async implementation once; the sync one is derived token by token
(``async def`` → ``def``, ``await x`` → ``x``, ``async for/with`` → ``for/with``,
``aget`` → ``get``, ``AsyncIterator`` → ``Iterator``...)::

    python -m ninja_devx.tooling.unasync src/orders/aio.py:src/orders/sync.py
    python -m ninja_devx.tooling.unasync src/orders/aio.py:src/orders/sync.py --check   # CI
    python -m ninja_devx.tooling.unasync a.py:b.py --replace AsyncOrderRepository=OrderRepository

Names are replaced as whole tokens (strings and comments are left alone, except the
generated-file header). Django's async ORM methods, this package's ``a``-prefixed
helpers and the standard async protocol names are mapped by default.
"""

from __future__ import annotations

import argparse
import io
import sys
import tokenize
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from types import MappingProxyType
from typing import Final

__all__ = ["DEFAULT_REPLACEMENTS", "Rule", "main", "unasync_source"]

DEFAULT_REPLACEMENTS: Final[Mapping[str, str]] = MappingProxyType(
    {
        # Python async protocols
        "AsyncIterator": "Iterator",
        "AsyncIterable": "Iterable",
        "AsyncGenerator": "Generator",
        "AsyncExitStack": "ExitStack",
        "AbstractAsyncContextManager": "AbstractContextManager",
        "asynccontextmanager": "contextmanager",
        "StopAsyncIteration": "StopIteration",
        "__aenter__": "__enter__",
        "__aexit__": "__exit__",
        "__aiter__": "__iter__",
        "__anext__": "__next__",
        "anext": "next",
        "aclose": "close",
        "enter_async_context": "enter_context",
        # Django's async ORM and auth
        "aaggregate": "aggregate",
        "abulk_create": "bulk_create",
        "abulk_update": "bulk_update",
        "acontains": "contains",
        "acount": "count",
        "acreate": "create",
        "adelete": "delete",
        "aearliest": "earliest",
        "aexists": "exists",
        "aexplain": "explain",
        "afirst": "first",
        "aget": "get",
        "aget_or_create": "get_or_create",
        "ain_bulk": "in_bulk",
        "aiterator": "iterator",
        "alast": "last",
        "alatest": "latest",
        "arefresh_from_db": "refresh_from_db",
        "asave": "save",
        "aupdate": "update",
        "aupdate_or_create": "update_or_create",
        "aauthenticate": "authenticate",
        "ahas_perm": "has_perm",
        "ahas_perms": "has_perms",
        "aget_object_or_404": "get_object_or_404",
        # ninja_devx
        "aresolve": "resolve",
        "arequest_scope": "request_scope",
        "arequest_user": "request_user",
        "acurrent_user": "current_user",
        "arequest_context": "request_context",
        "aauthenticated_user": "authenticated_user",
        "ahas_permission": "has_permission",
        "ahas_object_permission": "has_object_permission",
        "acheck_permissions": "check_permissions",
        "acheck_object_permissions": "check_object_permissions",
        "aget_object": "get_object",
        "aadd": "add",
        "achange": "change",
        "aremove": "remove",
        "AsyncRepository": "Repository",
        "AsyncResolver": "Resolver",
        "AsyncOperationHook": "OperationHook",
    }
)

_HEADER: Final = (
    "# Generated by `python -m ninja_devx.tooling.unasync` from:\n# {source}\n# Do not edit.\n"
)


@dataclass(frozen=True, slots=True)
class Rule:
    source: Path
    target: Path


def unasync_source(
    code: str, replacements: Mapping[str, str] = DEFAULT_REPLACEMENTS, *, header: str = ""
) -> str:
    """The sync version of ``code``."""
    lines = code.splitlines(keepends=True)
    offsets = [0]
    for line in lines:
        offsets.append(offsets[-1] + len(line))

    def position(row: int, column: int) -> int:
        return offsets[row - 1] + column

    edits: list[tuple[int, int, str]] = []
    tokens = list(tokenize.generate_tokens(io.StringIO(code).readline))
    for index, token in enumerate(tokens):
        if token.type != tokenize.NAME:
            continue
        start = position(*token.start)
        end = position(*token.end)
        following = tokens[index + 1] if index + 1 < len(tokens) else None
        if token.string == "await" or (
            token.string == "async"
            and following is not None
            and following.string in {"def", "for", "with"}
        ):
            next_start = position(*following.start) if following is not None else end
            edits.append((start, next_start, ""))
        elif (replacement := replacements.get(token.string)) is not None:
            edits.append((start, end, replacement))
    result = code
    for start, end, text in reversed(edits):
        result = result[:start] + text + result[end:]
    return header + result


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m ninja_devx.tooling.unasync", description=__doc__
    )
    parser.add_argument("rules", nargs="+", metavar="ASYNC.py:SYNC.py")
    parser.add_argument("--check", action="store_true", help="fail when a target is outdated")
    parser.add_argument(
        "--replace", action="append", default=[], metavar="OLD=NEW", help="extra name mapping"
    )
    arguments = parser.parse_args(argv)
    replacements = dict(DEFAULT_REPLACEMENTS)
    for item in arguments.replace:
        old, separator, new = str(item).partition("=")
        if not separator:
            parser.error(f"--replace expects OLD=NEW, got {item!r}")
        replacements[old] = new
    outdated: list[Path] = []
    for raw in arguments.rules:
        source, separator, target = str(raw).partition(":")
        if not separator:
            parser.error(f"expected ASYNC.py:SYNC.py, got {raw!r}")
        rule = Rule(Path(source), Path(target))
        generated = unasync_source(
            rule.source.read_text(),
            replacements,
            header=_HEADER.format(source=rule.source.as_posix()),
        )
        current = rule.target.read_text() if rule.target.exists() else None
        if current == generated:
            continue
        if arguments.check:
            outdated.append(rule.target)
        else:
            rule.target.write_text(generated)
            print(f"wrote {rule.target}")
    if outdated:
        names = ", ".join(str(path) for path in outdated)
        print(f"outdated (run without --check): {names}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
