"""Tests for the Post API: generated by ``manage.py devx_scaffold``."""

from collections.abc import Callable

import pytest
from ninja import NinjaAPI
from ninja.testing import TestClient

from blog.api.posts import PostController

pytestmark = pytest.mark.django_db


def test_post_openapi_builds() -> None:
    api = NinjaAPI()
    api.add_router("/posts", PostController.as_router())
    assert api.get_openapi_schema(path_prefix="")["paths"]


def test_post_list_requires_authentication(ninja_client: Callable[..., TestClient]) -> None:
    assert ninja_client(PostController).get("/").status_code == 401
