# Generated by Django 6.1.1 on 2026-09-13 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import ninja_devx.contrib.apikeys.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("prefix", models.CharField(max_length=16, unique=True)),
                ("hashed_secret", models.CharField(max_length=64)),
                ("scopes", models.JSONField(blank=True, default=list)),
                (
                    "rate_limit",
                    models.CharField(
                        blank=True,
                        help_text='Requests allowed for this key with APIKeyRateThrottle, e.g. "1000/hour".',
                        max_length=32,
                        validators=[ninja_devx.contrib.apikeys.models.validate_rate],
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API key",
                "ordering": ("-created",),
            },
        ),
    ]
