# ruff: noqa: E501, N815
"Generated by ninja-devx from Blog API 1.0.0. Do not edit."

from __future__ import annotations

import datetime as _dt
import uuid as _uuid
from collections.abc import Callable, Mapping
from typing import Annotated, Literal, NamedTuple, cast
from urllib.parse import quote

import httpx
from pydantic import BaseModel as _BaseModel
from pydantic import ConfigDict as _ConfigDict
from pydantic import Field as _Field
from pydantic import TypeAdapter as _TypeAdapter
from pydantic_core import to_jsonable_python as _to_jsonable_python

__all__ = ["ApiError", "UploadFile", "AsyncApiClient", "ApiClient"]


class UploadFile(NamedTuple):
    filename: str
    content: bytes
    content_type: str = "application/octet-stream"


class Input(_BaseModel):
    model_config = _ConfigDict(populate_by_name=True)

    page: Annotated[int, _Field(ge=1)] = 1
    page_size: Annotated[int | None, _Field(ge=1)] = None


class PostControllerFilters(_BaseModel):
    model_config = _ConfigDict(populate_by_name=True)

    search: str | None = None
    author: int | None = None
    status: Literal["draft", "published"] | None = None
    created__gte: _dt.datetime | None = None
    created__lte: _dt.datetime | None = None


class PostControllerOrdering(_BaseModel):
    model_config = _ConfigDict(populate_by_name=True)

    ordering: list[Literal["id", "-id", "created", "-created", "title", "-title"]] = []


class PagedPostOut(_BaseModel):
    model_config = _ConfigDict(populate_by_name=True)

    items: list[PostOut]
    count: int


class PostOut(_BaseModel):
    model_config = _ConfigDict(populate_by_name=True)

    id: int
    author_id: int
    title: str
    slug: str
    body: str
    status: Literal["draft", "published"]
    created: _dt.datetime
    deleted_at: _dt.datetime | None
    tags: list[int]


class PostIn(_BaseModel):
    model_config = _ConfigDict(populate_by_name=True)

    title: Annotated[str, _Field(min_length=1, max_length=200)]
    slug: Annotated[str, _Field(min_length=1, max_length=50, pattern="^[-a-zA-Z0-9_]+$")]
    body: str = ""
    status: Literal["draft", "published"] = "draft"
    tags: list[int] = []


class PostInPatch(_BaseModel):
    model_config = _ConfigDict(populate_by_name=True)

    title: Annotated[str | None, _Field(min_length=1, max_length=200)] = None
    slug: Annotated[str | None, _Field(min_length=1, max_length=50, pattern="^[-a-zA-Z0-9_]+$")] = None
    body: str | None = None
    status: Literal["draft", "published"] | None = None
    tags: list[int] | None = None


class CommentControllerOrdering(_BaseModel):
    model_config = _ConfigDict(populate_by_name=True)

    ordering: list[Literal["created", "-created"]] = []


EmptyFilters = dict[str, object]


class CommentOut(_BaseModel):
    model_config = _ConfigDict(populate_by_name=True)

    id: int
    post_id: int
    body: str
    created: _dt.datetime


class PagedCommentOut(_BaseModel):
    model_config = _ConfigDict(populate_by_name=True)

    items: list[CommentOut]
    count: int


class CommentIn(_BaseModel):
    model_config = _ConfigDict(populate_by_name=True)

    body: str


class CommentInPatch(_BaseModel):
    model_config = _ConfigDict(populate_by_name=True)

    body: str | None = None


class TagControllerFilters(_BaseModel):
    model_config = _ConfigDict(populate_by_name=True)

    search: str | None = None


class TagControllerOrdering(_BaseModel):
    model_config = _ConfigDict(populate_by_name=True)

    ordering: list[Literal["name", "-name"]] = []


class PagedTagOut(_BaseModel):
    model_config = _ConfigDict(populate_by_name=True)

    items: list[TagOut]
    count: int


class TagOut(_BaseModel):
    model_config = _ConfigDict(populate_by_name=True)

    id: int
    name: str


class ApiError(Exception):
    def __init__(
        self, status_code: int, body: object, headers: Mapping[str, str] | None = None
    ) -> None:
        super().__init__(f"Request failed with status {status_code}")
        self.status_code = status_code
        self.body = body
        self.headers = dict(headers or {})


_Primitive = str | int | float | bool | None


def _query(values: Mapping[str, object]) -> dict[str, _Primitive | list[_Primitive]]:
    return {
        key: cast("_Primitive | list[_Primitive]", _jsonable(value))
        for key, value in values.items()
        if value is not None
    }


def _path(value: object) -> str:
    return quote(str(_jsonable(value)), safe="")


def _jsonable(value: object) -> object:
    if isinstance(value, _BaseModel):
        return value.model_dump(mode="json", by_alias=True, exclude_unset=True)
    if isinstance(value, list | tuple):
        return [_jsonable(item) for item in value]
    if isinstance(value, Mapping):
        return {str(key): _jsonable(item) for key, item in value.items()}
    return _to_jsonable_python(value)


def _header_value(value: object) -> str:
    value = _jsonable(value)
    return str(value).lower() if isinstance(value, bool) else str(value)


def _headers(
    values: Mapping[str, object], extra: Mapping[str, str] | None, *, multipart: bool = False
) -> httpx.Headers:
    headers = httpx.Headers(extra)
    for name, value in values.items():
        if value is not None:
            headers[name] = (
                ",".join(_header_value(item) for item in value)
                if isinstance(value, list | tuple) else _header_value(value)
            )
    if multipart and "Content-Type" in headers:
        del headers["Content-Type"]
    return headers


def _decode(response: httpx.Response) -> object:
    media_type = response.headers.get("Content-Type", "").split(";", 1)[0].lower()
    body: object = None
    if response.content:
        if media_type == "application/json" or media_type.endswith("+json"):
            try:
                body = response.json()
            except ValueError:
                raise ApiError(response.status_code, response.text, response.headers) from None
        elif media_type.startswith("text/") or not response.is_success:
            body = response.text
        else:
            body = response.content
    if not response.is_success:
        raise ApiError(response.status_code, body, response.headers)
    return body

def _multipart_values(body: object) -> Mapping[str, object]:
    if isinstance(body, _BaseModel):
        return {
            info.alias or name: getattr(body, name)
            for name, info in type(body).model_fields.items()
            if name in body.model_fields_set
        }
    return cast("Mapping[str, object]", body or {})

def _multipart(body: object) -> tuple[dict[str, str], dict[str, tuple[str, bytes, str]]]:
    values = _multipart_values(body)
    fields: dict[str, str] = {}
    files: dict[str, tuple[str, bytes, str]] = {}
    for name, value in values.items():
        if value is None:
            continue
        if isinstance(value, UploadFile):
            files[name] = (value.filename, value.content, value.content_type)
        elif isinstance(value, bytes):
            files[name] = (name, value, "application/octet-stream")
        elif isinstance(value, str | int | float | bool):
            fields[name] = str(value).lower() if isinstance(value, bool) else str(value)
        else:
            raise TypeError(f"Unsupported multipart value for {name!r}")
    return fields, files

_RESULT_0: _TypeAdapter[PagedPostOut] = _TypeAdapter(PagedPostOut)
_RESULT_1: _TypeAdapter[PostOut] = _TypeAdapter(PostOut)
_RESULT_2: _TypeAdapter[PagedCommentOut] = _TypeAdapter(PagedCommentOut)
_RESULT_3: _TypeAdapter[CommentOut] = _TypeAdapter(CommentOut)
_RESULT_4: _TypeAdapter[PagedTagOut] = _TypeAdapter(PagedTagOut)
_RESULT_5: _TypeAdapter[TagOut] = _TypeAdapter(TagOut)


class ApiClient:
    """Client for the API."""

    def __init__(
        self,
        base_url: str = "",
        *,
        client: httpx.Client | None = None,
        headers: Mapping[str, str] | None = None,
    ) -> None:
        self._client = client or httpx.Client(base_url=base_url, headers=headers)

    def close(self) -> None:
        self._client.close()

    def __enter__(self) -> ApiClient:
        return self

    def __exit__(self, *exc_info: object) -> None:
        self.close()

    def v1_post_controller_list(
        self,
        *,
        search: str | None | None = None,
        author: int | None | None = None,
        status: Literal["draft", "published"] | None | None = None,
        created__gte: _dt.datetime | None | None = None,
        created__lte: _dt.datetime | None | None = None,
        ordering: list[Literal["id", "-id", "created", "-created", "title", "-title"]] | None = None,
        page: int | None = None,
        page_size: int | None | None = None,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> PagedPostOut:
        "List"
        response = self._client.request(
            "GET",
            "/api/v1/posts/",
            params=_query({"search": search, "author": author, "status": status, "created__gte": created__gte, "created__lte": created__lte, "ordering": ordering, "page": page, "page_size": page_size}),
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        return _RESULT_0.validate_python(_decode(response))

    def v1_post_controller_create(
        self,
        body: PostIn,
        *,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> PostOut:
        "Create"
        response = self._client.request(
            "POST",
            "/api/v1/posts/",
            json=_jsonable(body),
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        return _RESULT_1.validate_python(_decode(response))

    def v1_post_controller_retrieve(
        self,
        pk: int,
        *,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> PostOut:
        "Retrieve"
        response = self._client.request(
            "GET",
            "/api/v1/posts/" + _path(pk),
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        return _RESULT_1.validate_python(_decode(response))

    def v1_post_controller_update(
        self,
        pk: int,
        body: PostIn,
        *,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> PostOut:
        "Update"
        response = self._client.request(
            "PUT",
            "/api/v1/posts/" + _path(pk),
            json=_jsonable(body),
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        return _RESULT_1.validate_python(_decode(response))

    def v1_post_controller_partial_update(
        self,
        pk: int,
        body: PostInPatch,
        *,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> PostOut:
        "Partial Update"
        response = self._client.request(
            "PATCH",
            "/api/v1/posts/" + _path(pk),
            json=_jsonable(body),
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        return _RESULT_1.validate_python(_decode(response))

    def v1_post_controller_destroy(
        self,
        pk: int,
        *,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> None:
        "Destroy"
        response = self._client.request(
            "DELETE",
            "/api/v1/posts/" + _path(pk),
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        _decode(response)

    def v1_post_controller_restore(
        self,
        pk: int,
        *,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> PostOut:
        "Restore"
        response = self._client.request(
            "POST",
            "/api/v1/posts/" + _path(pk) + "/restore",
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        return _RESULT_1.validate_python(_decode(response))

    def v1_post_controller_publish(
        self,
        pk: int,
        *,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> PostOut:
        "Publish"
        response = self._client.request(
            "POST",
            "/api/v1/posts/" + _path(pk) + "/publish",
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        return _RESULT_1.validate_python(_decode(response))

    def v1_comment_controller_list(
        self,
        post_pk: int,
        *,
        ordering: list[Literal["created", "-created"]] | None = None,
        page: int | None = None,
        page_size: int | None | None = None,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> PagedCommentOut:
        "List"
        response = self._client.request(
            "GET",
            "/api/v1/posts/" + _path(post_pk) + "/comments/",
            params=_query({"ordering": ordering, "page": page, "page_size": page_size}),
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        return _RESULT_2.validate_python(_decode(response))

    def v1_comment_controller_create(
        self,
        post_pk: int,
        body: CommentIn,
        *,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> CommentOut:
        "Create"
        response = self._client.request(
            "POST",
            "/api/v1/posts/" + _path(post_pk) + "/comments/",
            json=_jsonable(body),
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        return _RESULT_3.validate_python(_decode(response))

    def v1_comment_controller_retrieve(
        self,
        pk: int,
        post_pk: int,
        *,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> CommentOut:
        "Retrieve"
        response = self._client.request(
            "GET",
            "/api/v1/posts/" + _path(post_pk) + "/comments/" + _path(pk),
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        return _RESULT_3.validate_python(_decode(response))

    def v1_comment_controller_update(
        self,
        pk: int,
        post_pk: int,
        body: CommentIn,
        *,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> CommentOut:
        "Update"
        response = self._client.request(
            "PUT",
            "/api/v1/posts/" + _path(post_pk) + "/comments/" + _path(pk),
            json=_jsonable(body),
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        return _RESULT_3.validate_python(_decode(response))

    def v1_comment_controller_partial_update(
        self,
        pk: int,
        post_pk: int,
        body: CommentInPatch,
        *,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> CommentOut:
        "Partial Update"
        response = self._client.request(
            "PATCH",
            "/api/v1/posts/" + _path(post_pk) + "/comments/" + _path(pk),
            json=_jsonable(body),
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        return _RESULT_3.validate_python(_decode(response))

    def v1_comment_controller_destroy(
        self,
        pk: int,
        post_pk: int,
        *,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> None:
        "Destroy"
        response = self._client.request(
            "DELETE",
            "/api/v1/posts/" + _path(post_pk) + "/comments/" + _path(pk),
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        _decode(response)

    def v1_tag_controller_list(
        self,
        *,
        search: str | None | None = None,
        ordering: list[Literal["name", "-name"]] | None = None,
        page: int | None = None,
        page_size: int | None | None = None,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> PagedTagOut:
        "List"
        response = self._client.request(
            "GET",
            "/api/v1/tags/",
            params=_query({"search": search, "ordering": ordering, "page": page, "page_size": page_size}),
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        return _RESULT_4.validate_python(_decode(response))

    def v1_tag_controller_retrieve(
        self,
        pk: int,
        *,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> TagOut:
        "Retrieve"
        response = self._client.request(
            "GET",
            "/api/v1/tags/" + _path(pk),
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        return _RESULT_5.validate_python(_decode(response))

class AsyncApiClient:
    """Async client for the API."""

    def __init__(
        self,
        base_url: str = "",
        *,
        client: httpx.AsyncClient | None = None,
        headers: Mapping[str, str] | None = None,
    ) -> None:
        self._client = client or httpx.AsyncClient(base_url=base_url, headers=headers)

    async def aclose(self) -> None:
        await self._client.aclose()

    async def __aenter__(self) -> AsyncApiClient:
        return self

    async def __aexit__(self, *exc_info: object) -> None:
        await self.aclose()

    async def v1_post_controller_list(
        self,
        *,
        search: str | None | None = None,
        author: int | None | None = None,
        status: Literal["draft", "published"] | None | None = None,
        created__gte: _dt.datetime | None | None = None,
        created__lte: _dt.datetime | None | None = None,
        ordering: list[Literal["id", "-id", "created", "-created", "title", "-title"]] | None = None,
        page: int | None = None,
        page_size: int | None | None = None,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> PagedPostOut:
        "List"
        response = await self._client.request(
            "GET",
            "/api/v1/posts/",
            params=_query({"search": search, "author": author, "status": status, "created__gte": created__gte, "created__lte": created__lte, "ordering": ordering, "page": page, "page_size": page_size}),
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        return _RESULT_0.validate_python(_decode(response))

    async def v1_post_controller_create(
        self,
        body: PostIn,
        *,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> PostOut:
        "Create"
        response = await self._client.request(
            "POST",
            "/api/v1/posts/",
            json=_jsonable(body),
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        return _RESULT_1.validate_python(_decode(response))

    async def v1_post_controller_retrieve(
        self,
        pk: int,
        *,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> PostOut:
        "Retrieve"
        response = await self._client.request(
            "GET",
            "/api/v1/posts/" + _path(pk),
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        return _RESULT_1.validate_python(_decode(response))

    async def v1_post_controller_update(
        self,
        pk: int,
        body: PostIn,
        *,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> PostOut:
        "Update"
        response = await self._client.request(
            "PUT",
            "/api/v1/posts/" + _path(pk),
            json=_jsonable(body),
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        return _RESULT_1.validate_python(_decode(response))

    async def v1_post_controller_partial_update(
        self,
        pk: int,
        body: PostInPatch,
        *,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> PostOut:
        "Partial Update"
        response = await self._client.request(
            "PATCH",
            "/api/v1/posts/" + _path(pk),
            json=_jsonable(body),
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        return _RESULT_1.validate_python(_decode(response))

    async def v1_post_controller_destroy(
        self,
        pk: int,
        *,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> None:
        "Destroy"
        response = await self._client.request(
            "DELETE",
            "/api/v1/posts/" + _path(pk),
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        _decode(response)

    async def v1_post_controller_restore(
        self,
        pk: int,
        *,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> PostOut:
        "Restore"
        response = await self._client.request(
            "POST",
            "/api/v1/posts/" + _path(pk) + "/restore",
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        return _RESULT_1.validate_python(_decode(response))

    async def v1_post_controller_publish(
        self,
        pk: int,
        *,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> PostOut:
        "Publish"
        response = await self._client.request(
            "POST",
            "/api/v1/posts/" + _path(pk) + "/publish",
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        return _RESULT_1.validate_python(_decode(response))

    async def v1_comment_controller_list(
        self,
        post_pk: int,
        *,
        ordering: list[Literal["created", "-created"]] | None = None,
        page: int | None = None,
        page_size: int | None | None = None,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> PagedCommentOut:
        "List"
        response = await self._client.request(
            "GET",
            "/api/v1/posts/" + _path(post_pk) + "/comments/",
            params=_query({"ordering": ordering, "page": page, "page_size": page_size}),
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        return _RESULT_2.validate_python(_decode(response))

    async def v1_comment_controller_create(
        self,
        post_pk: int,
        body: CommentIn,
        *,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> CommentOut:
        "Create"
        response = await self._client.request(
            "POST",
            "/api/v1/posts/" + _path(post_pk) + "/comments/",
            json=_jsonable(body),
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        return _RESULT_3.validate_python(_decode(response))

    async def v1_comment_controller_retrieve(
        self,
        pk: int,
        post_pk: int,
        *,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> CommentOut:
        "Retrieve"
        response = await self._client.request(
            "GET",
            "/api/v1/posts/" + _path(post_pk) + "/comments/" + _path(pk),
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        return _RESULT_3.validate_python(_decode(response))

    async def v1_comment_controller_update(
        self,
        pk: int,
        post_pk: int,
        body: CommentIn,
        *,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> CommentOut:
        "Update"
        response = await self._client.request(
            "PUT",
            "/api/v1/posts/" + _path(post_pk) + "/comments/" + _path(pk),
            json=_jsonable(body),
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        return _RESULT_3.validate_python(_decode(response))

    async def v1_comment_controller_partial_update(
        self,
        pk: int,
        post_pk: int,
        body: CommentInPatch,
        *,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> CommentOut:
        "Partial Update"
        response = await self._client.request(
            "PATCH",
            "/api/v1/posts/" + _path(post_pk) + "/comments/" + _path(pk),
            json=_jsonable(body),
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        return _RESULT_3.validate_python(_decode(response))

    async def v1_comment_controller_destroy(
        self,
        pk: int,
        post_pk: int,
        *,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> None:
        "Destroy"
        response = await self._client.request(
            "DELETE",
            "/api/v1/posts/" + _path(post_pk) + "/comments/" + _path(pk),
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        _decode(response)

    async def v1_tag_controller_list(
        self,
        *,
        search: str | None | None = None,
        ordering: list[Literal["name", "-name"]] | None = None,
        page: int | None = None,
        page_size: int | None | None = None,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> PagedTagOut:
        "List"
        response = await self._client.request(
            "GET",
            "/api/v1/tags/",
            params=_query({"search": search, "ordering": ordering, "page": page, "page_size": page_size}),
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        return _RESULT_4.validate_python(_decode(response))

    async def v1_tag_controller_retrieve(
        self,
        pk: int,
        *,
        request_headers: Mapping[str, str] | None = None,
        on_response: Callable[[httpx.Response], None] | None = None,
    ) -> TagOut:
        "Retrieve"
        response = await self._client.request(
            "GET",
            "/api/v1/tags/" + _path(pk),
            headers=_headers({}, request_headers, multipart=False),
        )
        if on_response is not None:
            on_response(response)
        return _RESULT_5.validate_python(_decode(response))
