// "Generated by ninja-devx from Blog API 1.0.0. Do not edit."

export interface Input {
  page?: number;
  page_size?: number | null;
}

export interface PostControllerFilters {
  search?: string | null;
  author?: number | null;
  status?: "draft" | "published" | null;
  created__gte?: string | null;
  created__lte?: string | null;
}

export interface PostControllerOrdering {
  ordering?: Array<"id" | "-id" | "created" | "-created" | "title" | "-title">;
}

export interface PagedPostOut {
  items: Array<PostOut>;
  count: number;
}

export interface PostOut {
  id: number;
  author_id: number;
  title: string;
  slug: string;
  body: string;
  status: "draft" | "published";
  created: string;
  deleted_at: string | null;
  tags: Array<number>;
}

export interface PostIn {
  title: string;
  slug: string;
  body?: string;
  status?: "draft" | "published";
  tags?: Array<number>;
}

export interface PostInPatch {
  title?: string | null;
  slug?: string | null;
  body?: string | null;
  status?: "draft" | "published" | null;
  tags?: Array<number> | null;
}

export interface CommentControllerOrdering {
  ordering?: Array<"created" | "-created">;
}

export type EmptyFilters = Record<string, unknown>;

export interface CommentOut {
  id: number;
  post_id: number;
  body: string;
  created: string;
}

export interface PagedCommentOut {
  items: Array<CommentOut>;
  count: number;
}

export interface CommentIn {
  body: string;
}

export interface CommentInPatch {
  body?: string | null;
}

export interface TagControllerFilters {
  search?: string | null;
}

export interface TagControllerOrdering {
  ordering?: Array<"name" | "-name">;
}

export interface PagedTagOut {
  items: Array<TagOut>;
  count: number;
}

export interface TagOut {
  id: number;
  name: string;
}

export class ApiError extends Error {
  constructor(
    readonly status: number,
    readonly body: unknown,
    readonly headers?: Headers,
  ) {
    super(`Request failed with status ${status}`);
  }
}

export interface ClientOptions {
  baseUrl?: string;
  headers?: Record<string, string> | (() => Record<string, string>);
  fetch?: typeof fetch;
}

export interface RequestOptions {
  headers?: Record<string, string>;
  onResponse?: (response: Response) => void;
}

function multipart(body: object | undefined): FormData | undefined {
  if (body === undefined) return undefined;
  const form = new FormData();
  for (const [key, value] of Object.entries(body)) {
    if (value == null) continue;
    if (value instanceof Blob) form.append(key, value);
    else if (["string", "number", "boolean"].includes(typeof value)) {
      form.append(key, String(value));
    }
    else throw new TypeError(`Unsupported multipart value for ${key}`);
  }
  return form;
}

type QueryValue = string | number | boolean | null | undefined | Array<string | number | boolean>;

function buildUrl(baseUrl: string, path: string, query?: Record<string, QueryValue>): string {
  const search = new URLSearchParams();
  for (const [key, value] of Object.entries(query ?? {})) {
    if (value === null || value === undefined) continue;
    for (const item of Array.isArray(value) ? value : [value]) search.append(key, String(item));
  }
  const suffix = search.toString();
  return `${baseUrl.replace(/\/$/, "")}${path}${suffix ? `?${suffix}` : ""}`;
}

export function createClient(options: ClientOptions = {}) {
  const baseUrl = options.baseUrl ?? "";
  const fetchImpl = options.fetch ?? fetch;
  async function request<T>(
    method: string,
    path: string,
    query?: Record<string, QueryValue>,
    body?: unknown,
    declaredHeaders?: Record<string, unknown>,
    requestOptions: RequestOptions = {},
  ): Promise<T> {
    const headers = new Headers({ Accept: "application/json" });
    const extra =
      typeof options.headers === "function" ? options.headers() : options.headers;
    for (const [key, value] of Object.entries({...extra, ...requestOptions.headers})) {
      headers.set(key, value);
    }
    for (const [key, value] of Object.entries(declaredHeaders ?? {})) {
      if (value != null) {
        headers.set(key, Array.isArray(value) ? value.join(',') : String(value));
      }
    }
    if (body instanceof FormData) headers.delete("Content-Type");
    else if (body !== undefined) headers.set("Content-Type", "application/json");
    const response = await fetchImpl(buildUrl(baseUrl, path, query), {
      method,
      headers,
      body: body instanceof FormData ? body :
        body === undefined ? undefined : JSON.stringify(body),
    });
    requestOptions.onResponse?.(response);
    const mediaType =
      (response.headers.get('Content-Type') ?? '').split(';')[0].toLowerCase();
    const raw = await response.arrayBuffer();
    let data: unknown;
    if (raw.byteLength) {
      if (mediaType === 'application/json' || mediaType.endsWith('+json')) {
        const text = new TextDecoder().decode(raw);
        try { data = JSON.parse(text); } catch {
          throw new ApiError(response.status, text, response.headers);
        }
      } else if (mediaType.startsWith('text/') || !response.ok) {
        data = new TextDecoder().decode(raw);
      } else { data = new Uint8Array(raw); }
    }
    if (!response.ok) throw new ApiError(response.status, data, response.headers);
    return data as T;
  }

  return {
    // "List"
    v1PostControllerList: (query: { search?: string | null; author?: number | null; status?: "draft" | "published" | null; created__gte?: string | null; created__lte?: string | null; ordering?: Array<"id" | "-id" | "created" | "-created" | "title" | "-title">; page?: number; page_size?: number | null } = {}, requestOptions: RequestOptions = {}) =>
      request<PagedPostOut>("GET", "/api/v1/posts/", query, undefined, undefined, requestOptions),
    // "Create"
    v1PostControllerCreate: (body: PostIn, requestOptions: RequestOptions = {}) =>
      request<PostOut>("POST", "/api/v1/posts/", undefined, body, undefined, requestOptions),
    // "Retrieve"
    v1PostControllerRetrieve: (pk: number, requestOptions: RequestOptions = {}) =>
      request<PostOut>("GET", "/api/v1/posts/" + encodeURIComponent(String(pk)), undefined, undefined, undefined, requestOptions),
    // "Update"
    v1PostControllerUpdate: (pk: number, body: PostIn, requestOptions: RequestOptions = {}) =>
      request<PostOut>("PUT", "/api/v1/posts/" + encodeURIComponent(String(pk)), undefined, body, undefined, requestOptions),
    // "Partial Update"
    v1PostControllerPartialUpdate: (pk: number, body: PostInPatch, requestOptions: RequestOptions = {}) =>
      request<PostOut>("PATCH", "/api/v1/posts/" + encodeURIComponent(String(pk)), undefined, body, undefined, requestOptions),
    // "Destroy"
    v1PostControllerDestroy: (pk: number, requestOptions: RequestOptions = {}) =>
      request<void>("DELETE", "/api/v1/posts/" + encodeURIComponent(String(pk)), undefined, undefined, undefined, requestOptions),
    // "Restore"
    v1PostControllerRestore: (pk: number, requestOptions: RequestOptions = {}) =>
      request<PostOut>("POST", "/api/v1/posts/" + encodeURIComponent(String(pk)) + "/restore", undefined, undefined, undefined, requestOptions),
    // "Publish"
    v1PostControllerPublish: (pk: number, requestOptions: RequestOptions = {}) =>
      request<PostOut>("POST", "/api/v1/posts/" + encodeURIComponent(String(pk)) + "/publish", undefined, undefined, undefined, requestOptions),
    // "List"
    v1CommentControllerList: (post_pk: number, query: { ordering?: Array<"created" | "-created">; page?: number; page_size?: number | null } = {}, requestOptions: RequestOptions = {}) =>
      request<PagedCommentOut>("GET", "/api/v1/posts/" + encodeURIComponent(String(post_pk)) + "/comments/", query, undefined, undefined, requestOptions),
    // "Create"
    v1CommentControllerCreate: (post_pk: number, body: CommentIn, requestOptions: RequestOptions = {}) =>
      request<CommentOut>("POST", "/api/v1/posts/" + encodeURIComponent(String(post_pk)) + "/comments/", undefined, body, undefined, requestOptions),
    // "Retrieve"
    v1CommentControllerRetrieve: (pk: number, post_pk: number, requestOptions: RequestOptions = {}) =>
      request<CommentOut>("GET", "/api/v1/posts/" + encodeURIComponent(String(post_pk)) + "/comments/" + encodeURIComponent(String(pk)), undefined, undefined, undefined, requestOptions),
    // "Update"
    v1CommentControllerUpdate: (pk: number, post_pk: number, body: CommentIn, requestOptions: RequestOptions = {}) =>
      request<CommentOut>("PUT", "/api/v1/posts/" + encodeURIComponent(String(post_pk)) + "/comments/" + encodeURIComponent(String(pk)), undefined, body, undefined, requestOptions),
    // "Partial Update"
    v1CommentControllerPartialUpdate: (pk: number, post_pk: number, body: CommentInPatch, requestOptions: RequestOptions = {}) =>
      request<CommentOut>("PATCH", "/api/v1/posts/" + encodeURIComponent(String(post_pk)) + "/comments/" + encodeURIComponent(String(pk)), undefined, body, undefined, requestOptions),
    // "Destroy"
    v1CommentControllerDestroy: (pk: number, post_pk: number, requestOptions: RequestOptions = {}) =>
      request<void>("DELETE", "/api/v1/posts/" + encodeURIComponent(String(post_pk)) + "/comments/" + encodeURIComponent(String(pk)), undefined, undefined, undefined, requestOptions),
    // "List"
    v1TagControllerList: (query: { search?: string | null; ordering?: Array<"name" | "-name">; page?: number; page_size?: number | null } = {}, requestOptions: RequestOptions = {}) =>
      request<PagedTagOut>("GET", "/api/v1/tags/", query, undefined, undefined, requestOptions),
    // "Retrieve"
    v1TagControllerRetrieve: (pk: number, requestOptions: RequestOptions = {}) =>
      request<TagOut>("GET", "/api/v1/tags/" + encodeURIComponent(String(pk)), undefined, undefined, undefined, requestOptions),
  };
}

export type ApiClient = ReturnType<typeof createClient>;
