"""Generate the configuration reference (``docs/options/*.md``) from the source code.

Every table (option, attribute, parameter, setting, command flag, error code) is read from
the code itself: types and defaults from the AST exactly as written, descriptions from
attribute docstrings and ``:param name:`` lines. The docs cannot drift from the code:
``tests/test_generated_docs.py`` fails when a page is outdated.

::

    uv run python tools/generate_docs.py          # write
    uv run python tools/generate_docs.py --check  # CI
"""

from __future__ import annotations

import argparse
import ast
import importlib
import inspect
import os
import re
import sys
import tomllib
from collections.abc import Callable, Iterable, Sequence
from dataclasses import dataclass, field
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src"
OUTPUT = ROOT / "docs" / "options"
HEADER = "<!-- Generated by tools/generate_docs.py from the source code; do not edit. -->\n\n"


# --- Reading the source ------------------------------------------------------------------


def _module_path(module: str) -> Path:
    base = SOURCE / Path(*module.split("."))
    return base / "__init__.py" if base.is_dir() else base.with_suffix(".py")


_trees: dict[str, ast.Module] = {}


def _tree(module: str) -> ast.Module:
    if module not in _trees:
        _trees[module] = ast.parse(_module_path(module).read_text())
    return _trees[module]


def _find(module: str, qualname: str) -> ast.ClassDef | ast.FunctionDef | ast.AsyncFunctionDef:
    nodes: Sequence[ast.stmt] = _tree(module).body
    found: ast.stmt | None = None
    for part in qualname.split("."):
        matches = [
            node
            for node in nodes
            if isinstance(node, ast.ClassDef | ast.FunctionDef | ast.AsyncFunctionDef)
            and node.name == part
        ]
        found = matches[-1] if matches else None  # the implementation after any @overload
        if found is None:
            raise LookupError(f"{module}:{qualname} not found")
        nodes = found.body if isinstance(found, ast.ClassDef) else []
    assert isinstance(found, ast.ClassDef | ast.FunctionDef | ast.AsyncFunctionDef)
    return found


def _rst(text: str) -> str:
    """RST-ish docstring text as one Markdown line."""
    text = re.sub(r"``([^`]+)``", r"`\1`", text)
    text = re.sub(r":(?:class|func|meth|attr):`~?([^`]+)`", r"`\1`", text)
    return " ".join(text.split())


def _paragraph(doc: str | None) -> str:
    if not doc:
        return ""
    return _rst(inspect.cleandoc(doc).split("\n\n")[0])


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def _code(text: str) -> str:
    return f"`{_cell(text)}`" if text else ""


def _unwrap_classvar(annotation: ast.expr) -> ast.expr:
    if (
        isinstance(annotation, ast.Subscript)
        and isinstance(annotation.value, ast.Name)
        and annotation.value.id in {"ClassVar", "Final"}
    ):
        return annotation.slice
    return annotation


def _attribute_doc(body: Sequence[ast.stmt], index: int) -> str:
    following = body[index + 1] if index + 1 < len(body) else None
    if (
        isinstance(following, ast.Expr)
        and isinstance(following.value, ast.Constant)
        and isinstance(following.value.value, str)
    ):
        return _paragraph(following.value.value)
    return ""


@dataclass
class Attribute:
    name: str
    type: str
    default: str
    doc: str


def attributes(module: str, qualname: str, *, public_only: bool = True) -> list[Attribute]:
    node = _find(module, qualname)
    assert isinstance(node, ast.ClassDef)
    found: list[Attribute] = []
    for index, statement in enumerate(node.body):
        if not (isinstance(statement, ast.AnnAssign) and isinstance(statement.target, ast.Name)):
            continue
        name = statement.target.id
        if public_only and name.startswith("_"):
            continue
        default = ast.unparse(statement.value) if statement.value is not None else ""
        found.append(
            Attribute(
                name,
                ast.unparse(_unwrap_classvar(statement.annotation)),
                default,
                _attribute_doc(node.body, index),
            )
        )
    return found


def class_doc(module: str, qualname: str) -> str:
    return _paragraph(ast.get_docstring(_find(module, qualname)))


@dataclass
class Parameter:
    name: str
    type: str
    default: str
    kind: str
    doc: str


def _param_docs(doc: str | None) -> dict[str, str]:
    found: dict[str, str] = {}
    if not doc:
        return found
    current: str | None = None
    for line in inspect.cleandoc(doc).splitlines():
        if match := re.match(r"\s*:param (\*{0,2}\w+):\s*(.*)", line):
            current = match.group(1).lstrip("*")
            found[current] = match.group(2)
        elif current and line.startswith((" ", "\t")) and line.strip():
            found[current] += " " + line.strip()
        else:
            current = None
    return {name: _rst(text) for name, text in found.items()}


def _description(doc: str | None) -> str:
    if not doc:
        return ""
    kept = [
        line
        for line in inspect.cleandoc(doc).split("\n\n")
        if not line.lstrip().startswith(":param")
    ]
    return _rst(kept[0]) if kept else ""


def parameters(module: str, qualname: str) -> tuple[list[Parameter], str, str]:
    node = _find(module, qualname)
    if isinstance(node, ast.ClassDef):
        init = next(
            (s for s in node.body if isinstance(s, ast.FunctionDef) and s.name == "__init__"), None
        )
        if init is None:
            raise LookupError(f"{qualname} has no __init__")
        function: ast.FunctionDef | ast.AsyncFunctionDef = init
        doc = ast.get_docstring(node) or ""
        init_doc = ast.get_docstring(init) or ""
        docs = {**_param_docs(doc), **_param_docs(init_doc)}
        summary = _description(doc)
    else:
        function = node
        doc = ast.get_docstring(node) or ""
        docs = _param_docs(doc)
        summary = _description(doc)
    arguments = function.args
    found: list[Parameter] = []
    positional = [*arguments.posonlyargs, *arguments.args]
    defaults: list[ast.expr | None] = [None] * (len(positional) - len(arguments.defaults)) + list(
        arguments.defaults
    )
    for index, (argument, default) in enumerate(zip(positional, defaults, strict=True)):
        if argument.arg in {"self", "cls"}:
            continue
        kind = "positional-only" if index < len(arguments.posonlyargs) else ""
        found.append(_parameter(argument, default, kind, docs))
    if arguments.vararg:
        found.append(_parameter(arguments.vararg, None, "*args", docs))
    for argument, default in zip(arguments.kwonlyargs, arguments.kw_defaults, strict=True):
        found.append(_parameter(argument, default, "keyword-only", docs))
    if arguments.kwarg:
        found.append(_parameter(arguments.kwarg, None, "**kwargs", docs))
    returns = ast.unparse(function.returns) if function.returns is not None else ""
    return found, summary, returns


def _parameter(
    argument: ast.arg, default: ast.expr | None, kind: str, docs: dict[str, str]
) -> Parameter:
    annotation = ast.unparse(argument.annotation) if argument.annotation is not None else ""
    return Parameter(
        argument.arg,
        annotation,
        ast.unparse(default) if default is not None else "",
        kind,
        docs.get(argument.arg, ""),
    )


# --- Blocks ------------------------------------------------------------------------------


class Block:
    def render(self) -> str:
        raise NotImplementedError


@dataclass
class Text(Block):
    markdown: str

    def render(self) -> str:
        return inspect.cleandoc(self.markdown) + "\n"


@dataclass
class Attributes(Block):
    """Class attributes, TypedDict keys or dataclass fields."""

    target: str
    title: str | None = None
    note: str = ""
    defaults: Callable[[str], str] | None = None
    exclude: Sequence[str] = ()
    required_label: bool = False

    def render(self) -> str:
        module, qualname = self.target.split(":")
        rows = [a for a in attributes(module, qualname) if a.name not in self.exclude]
        title = self.title or f"`{qualname}`"
        lines = [f"### {title}", ""]
        if doc := class_doc(module, qualname):
            lines += [doc, ""]
        if self.note:
            lines += [inspect.cleandoc(self.note), ""]
        lines += ["| Name | Type | Default | Description |", "|---|---|---|---|"]
        for row in rows:
            default = self.defaults(row.name) if self.defaults else row.default
            lines.append(
                f"| `{row.name}` | {_code(row.type)} | {_code(default) or '—'} | {_cell(row.doc)} |"
            )
        return "\n".join(lines) + "\n"


@dataclass
class Signature(Block):
    target: str
    title: str | None = None
    display: str | None = None

    def render(self) -> str:
        module, qualname = self.target.split(":")
        params, summary, returns = parameters(module, qualname)
        name = self.display or qualname.split(".")[-1]
        title = self.title or f"`{name}()`"
        lines = [f"### {title}", ""]
        signature = ", ".join(_signature_part(p) for p in _with_markers(params))
        arrow = f" -> {returns}" if returns else ""
        function = name.rsplit(".", 1)[-1]
        lines += ["```python", f"def {function}({signature}){arrow}: ...", "```", ""]
        if summary:
            lines += [summary, ""]
        if params:
            lines += ["| Parameter | Type | Default | Description |", "|---|---|---|---|"]
            for p in params:
                label = {"*args": f"*{p.name}", "**kwargs": f"**{p.name}"}.get(p.kind, p.name)
                lines.append(
                    f"| `{label}` | {_code(p.type)} | {_code(p.default) or '—'} | {_cell(p.doc)} |"
                )
        return "\n".join(lines) + "\n"


def _with_markers(params: list[Parameter]) -> list[Parameter | str]:
    parts: list[Parameter | str] = []
    slash_done = False
    star_done = any(p.kind == "*args" for p in params)
    for p in params:
        if (
            not slash_done
            and p.kind != "positional-only"
            and any(q.kind == "positional-only" for q in params)
        ):
            parts.append("/")
            slash_done = True
        if p.kind == "keyword-only" and not star_done:
            parts.append("*")
            star_done = True
        parts.append(p)
    return parts


def _signature_part(part: Parameter | str) -> str:
    if isinstance(part, str):
        return part
    prefix = {"*args": "*", "**kwargs": "**"}.get(part.kind, "")
    text = f"{prefix}{part.name}"
    if part.type:
        text += f": {part.type}"
    if part.default:
        text += f" = {part.default}" if part.type else f"={part.default}"
    return text


@dataclass
class Classes(Block):
    """A table of classes with their constructor arguments and summary."""

    title: str
    targets: Sequence[str]
    header: tuple[str, str, str] = ("Class", "Arguments", "Description")

    def render(self) -> str:
        lines = [f"### {self.title}", "", f"| {' | '.join(self.header)} |", "|---|---|---|"]
        for target in self.targets:
            module, qualname = target.split(":")
            try:
                params, summary, _ = parameters(module, qualname)
                arguments = ", ".join(_signature_part(p) for p in _with_markers(params))
            except LookupError:
                fields = attributes(module, qualname)
                arguments = ", ".join(
                    f"{a.name}: {a.type}" + (f" = {a.default}" if a.default else "")
                    for a in fields
                    if not a.doc.startswith("Set by")
                )
                summary = class_doc(module, qualname)
            summary = summary or class_doc(module, qualname)
            lines.append(f"| `{qualname}` | {_code(arguments) or '—'} | {_cell(summary)} |")
        return "\n".join(lines) + "\n"


@dataclass
class Runtime(Block):
    """A table computed by importing the package (errors, commands, fixtures)."""

    build: Callable[[], str]

    def render(self) -> str:
        return self.build()


@dataclass
class Page:
    slug: str
    title: str
    intro: str
    blocks: list[Block] = field(default_factory=list)

    def render(self) -> str:
        parts = [HEADER + f"# {self.title}\n", inspect.cleandoc(self.intro) + "\n"]
        parts += [block.render() for block in self.blocks]
        return "\n".join(parts)


# --- Runtime tables ----------------------------------------------------------------------


def _settings_default(name: str) -> str:
    module, qualname = "ninja_devx.configuration.settings", "ResolvedSettings"
    defaults = {a.name: a.default for a in attributes(module, qualname)}
    value = defaults.get(name.lower(), "")
    if "default_factory" in value:
        match = re.search(r"default_factory=(?:lambda: )?([^)]*)", value)
        inner = match.group(1) if match else ""
        return "{}" if "dict" in inner or inner.startswith("cast") else inner + "()"
    return value


def domain_errors() -> str:
    from ninja_devx.layers.errors import DomainError

    rows: dict[str, type[DomainError]] = {}
    for module_name in (
        "ninja_devx.layers.errors",
        "ninja_devx.layers.policies",
        "ninja_devx.security.tenancy",
        "ninja_devx.http.conditional",
    ):
        module = importlib.import_module(module_name)
        for value in vars(module).values():
            if isinstance(value, type) and issubclass(value, DomainError):
                rows[f"{value.__module__}.{value.__qualname__}"] = value
    lines = [
        "### Built-in domain errors",
        "",
        "| Exception | Status | `code` | Default `detail` | Import |",
        "|---|---|---|---|---|",
    ]
    for _path, error in sorted(rows.items(), key=lambda item: (item[1].http_status, item[0])):
        doc = inspect.cleandoc(error.__doc__ or "").split("\n")[0]
        module = (
            error.__module__.removesuffix(".errors")
            if "layers" in error.__module__
            else error.__module__
        )
        lines.append(
            f"| `{error.__qualname__}` | {error.http_status} | `{error.code}` | {_cell(doc)} | `{module}` |"
        )
    return "\n".join(lines) + "\n"


def exceptions_and_warnings() -> str:
    from ninja_devx import exceptions

    lines = ["### Exceptions and warnings", "", "| Class | Base | When |", "|---|---|---|"]
    classes = [
        value
        for value in vars(exceptions).values()
        if isinstance(value, type)
        and issubclass(value, BaseException)
        and value.__module__ == exceptions.__name__
    ]
    for value in classes:
        name = value.__qualname__
        base = value.__bases__[0].__name__
        lines.append(f"| `{name}` | `{base}` | {_cell(_paragraph(value.__doc__))} |")
    return "\n".join(lines) + "\n"


def management_command(name: str, app: str = "ninja_devx") -> Callable[[], str]:
    def build() -> str:
        from django.core.management import load_command_class

        command = load_command_class(app, name)
        parser = command.create_parser("manage.py", name)
        lines = [
            f"### `manage.py {name}`",
            "",
            _rst(command.help),
            "",
            "| Argument | Type | Default | Description |",
            "|---|---|---|---|",
        ]
        builtin = {
            "--version", "-v", "--verbosity", "--settings", "--pythonpath", "--traceback",
            "--no-color", "--force-color", "--skip-checks", "-h", "--help",
        }  # fmt: skip
        for action in parser._actions:
            flags = [flag for flag in action.option_strings if flag not in builtin]
            if action.option_strings and not flags:
                continue
            label = ", ".join(flags) if flags else action.dest
            kind = (
                "flag"
                if isinstance(action, argparse._StoreTrueAction)
                else "one of " + ", ".join(f"`{c}`" for c in action.choices)
                if action.choices
                else ("list" if action.nargs in ("+", "*") else "value")
            )
            default = (
                "" if action.default in (None, False, argparse.SUPPRESS) else repr(action.default)
            )
            if isinstance(action.default, str) and os.path.isabs(action.default):
                default = "the ninja-devx app template"  # machine-specific path
            lines.append(
                f"| `{label}` | {kind} | {_code(default) or '—'} | {_cell(action.help or '')} |"
            )
        return "\n".join(lines) + "\n"

    return build


def template_command(name: str, django_name: str) -> Callable[[], str]:
    # Django's startapp/startproject options (and their help texts) differ between Django
    # versions, so only the options ninja-devx adds are read from the parser.
    def build() -> str:
        from django.core.management import load_command_class

        command = load_command_class("ninja_devx", name)
        base = load_command_class("django.core", django_name).create_parser("manage.py", name)
        inherited = {action.dest for action in base._actions}
        lines = [
            f"### `manage.py {name}`",
            "",
            _rst(command.help),
            "",
            "| Argument | Type | Default | Description |",
            "|---|---|---|---|",
            f"| `name` | value | — | Name of the {django_name.removeprefix('start')}. |",
            "| `directory` | value | — | Optional destination directory, created if needed. |",
            "| `--template` | value | the ninja-devx template | Another template directory or archive. |",
        ]
        for action in command.create_parser("manage.py", name)._actions:
            if action.dest in inherited:
                continue
            kind = "flag" if isinstance(action, argparse._StoreTrueAction) else "value"
            label = ", ".join(action.option_strings)
            lines.append(f"| `{label}` | {kind} | — | {_cell(action.help or '')} |")
        lines += [
            "",
            f"Every other option of Django's `{django_name}` (`--extension`, `--name`, "
            "`--exclude`) is accepted.",
            "",
        ]
        return "\n".join(lines)

    return build


def unasync_cli() -> str:
    from ninja_devx.tooling.unasync import DEFAULT_REPLACEMENTS

    names = ", ".join(f"`{old}` → `{new}`" for old, new in sorted(DEFAULT_REPLACEMENTS.items()))
    return (
        inspect.cleandoc(
            f"""
        ### `python -m ninja_devx.tooling.unasync`

        | Argument | Type | Default | Description |
        |---|---|---|---|
        | `ASYNC.py:SYNC.py` | one or more pairs | — | source (async) and generated (sync) files |
        | `--check` | flag | — | fail when a generated file is outdated |
        | `--replace OLD=NEW` | repeatable | — | extra name mapping |

        Default renames: {names}.
        """
        )
        + "\n"
    )


def pytest_plugin() -> str:
    tree = _tree("ninja_devx.testing.plugin")
    fixtures: list[str] = []
    options: list[str] = []
    for node in tree.body:
        if isinstance(node, ast.FunctionDef) and any(
            ast.unparse(d).startswith("pytest.fixture") for d in node.decorator_list
        ):
            returns = ast.unparse(node.returns) if node.returns else ""
            fixtures.append(
                f"| `{node.name}` | {_code(returns)} | {_cell(_paragraph(ast.get_docstring(node)))} |"
            )
        if isinstance(node, ast.FunctionDef) and node.name == "pytest_addoption":
            for call in ast.walk(node):
                if not (isinstance(call, ast.Call) and isinstance(call.func, ast.Attribute)):
                    continue
                keywords = {k.arg: k.value for k in call.keywords}
                name = ast.literal_eval(call.args[0]) if call.args else ""
                help_text = ast.literal_eval(keywords["help"]) if "help" in keywords else ""
                default = ast.unparse(keywords["default"]) if "default" in keywords else ""
                where = "command line" if call.func.attr == "addoption" else "ini"
                options.append(f"| `{name}` | {where} | {_code(default)} | {_cell(help_text)} |")
    return (
        "\n".join(
            [
                "### Fixtures",
                "",
                "| Fixture | Returns | Description |",
                "|---|---|---|",
                *fixtures,
                "",
                "### Options",
                "",
                "| Option | Where | Default | Description |",
                "|---|---|---|---|",
                *options,
            ]
        )
        + "\n"
    )


def system_checks() -> str:
    from ninja_devx.configuration.checks import CHECKS

    lines = ["### System checks", "", "| Id | Level | Problem |", "|---|---|---|"]
    for identifier, (level, message) in CHECKS.items():
        lines.append(f"| `{identifier}` | {level} | {_cell(_rst(message))} |")
    return "\n".join(lines) + "\n"


# --- Pages -------------------------------------------------------------------------------


def pages() -> list[Page]:
    ops = "ninja_devx.routing.operations"
    crud = "ninja_devx.crud.controllers"
    return [
        Page(
            "controllers",
            "Controllers and operations",
            """
            Everything a controller, an operation decorator, `routes` and `mount()` accept.
            Options merge in this order, later layers winning: `NINJA_DEVX["DEFAULT_OPTIONS"]`,
            `Controller.options` along the MRO, `as_router(**options)`, operation options.
            See the [Controllers guide](../guide/controllers.md).
            """,
            [
                Attributes(
                    "ninja_devx.routing.controller:Controller",
                    title="`Controller` class attributes",
                ),
                Signature(
                    "ninja_devx.routing.controller:Controller.as_router",
                    display="Controller.as_router",
                ),
                Attributes("ninja_devx.routing.controller:ControllerOptions"),
                Signature(f"{ops}:api_operation"),
                Text(
                    """
                    `get(path="/", **options)`, `post(...)`, `put(...)`, `patch(...)` and
                    `delete(...)` take the same `path` and options as `api_operation`.
                    """
                ),
                Attributes(f"{ops}:OperationOptions"),
                Attributes(
                    f"{ops}:RouteOptions",
                    note="Also accepts every `OperationOptions` key.",
                ),
                Signature(f"{ops}:async_variant"),
                Signature("ninja_devx.routing.use_cases:use_case"),
                Signature("ninja_devx.routing.use_cases:use_query"),
                Classes(
                    "CQRS building blocks",
                    [
                        "ninja_devx.cqrs.messages:Message",
                        "ninja_devx.cqrs.messages:Command",
                        "ninja_devx.cqrs.messages:Query",
                        "ninja_devx.cqrs.events:DomainEvent",
                        "ninja_devx.cqrs.events:EventBus",
                        "ninja_devx.cqrs.unit_of_work:UnitOfWork",
                    ],
                ),
                Classes("Application plugins", ["ninja_devx.plugins:APIPlugin"]),
                Signature("ninja_devx.plugins:install"),
                Signature("ninja_devx.routing.mounting:mount"),
                Attributes("ninja_devx.routing.mounting:Mount"),
                Attributes("ninja_devx.routing.hooks:OperationInfo"),
                Attributes("ninja_devx.routing.hooks:LoggingHook"),
            ],
        ),
        Page(
            "crud",
            "CRUD",
            """
            Class attributes of the generic model controllers and their companions. Attributes
            left unset fall back to [settings](settings.md). See the [CRUD guide](../guide/crud.md).
            """,
            [
                Attributes(
                    f"{crud}:ModelController", title="`ModelController` (every model controller)"
                ),
                Attributes(
                    f"{crud}:ListConfig",
                    title="List options (`ListMixin`, `ReadOnlyModelController`, `CRUDController`)",
                ),
                Attributes("ninja_devx.crud.optimization:ExpandRule"),
                Attributes(
                    "ninja_devx.crud.auto:AutoSchemas",
                    title="Generated schemas (`AutoCRUDController`, `AutoReadOnlyController`)",
                ),
                Signature("ninja_devx.crud.auto:model_schemas"),
                Attributes("ninja_devx.crud.bulk:_BulkBase", title="Bulk options (`Bulk*Mixin`)"),
                Attributes("ninja_devx.crud.bulk:BulkErrorDetail"),
                Text(
                    """
                    `BulkResultOut`: `{"results": [{"index", "status", "data"} |
                    {"index", "status", "errors"}]}`, the body of a partial-success (207) bulk
                    response from `bulk_partial=True`; `errors` uses `BulkErrorDetail`, and the
                    response carries an `X-Bulk-Failed` count header.
                    """
                ),
                Attributes("ninja_devx.crud.nested_writes:NestedWritesMixin"),
                Attributes("ninja_devx.crud.nested_writes:Nested"),
                Attributes("ninja_devx.crud.transitions:TransitionsMixin"),
                Attributes("ninja_devx.crud.transitions:Transition"),
                Text(
                    """
                    ### `MetaMixin` (`GET /meta`)

                    Describes the input and output schemas for a form or admin UI: field
                    types, required/read-only, max length and enum choices, plus
                    `filter_fields`, `ordering_fields` and `search_fields`. No configuration.
                    """
                ),
                Classes(
                    "`MetaMixin` schemas",
                    [
                        "ninja_devx.crud.meta:ControllerMeta",
                        "ninja_devx.crud.meta:FieldMeta",
                        "ninja_devx.crud.meta:ChoiceOut",
                    ],
                ),
                Attributes("ninja_devx.crud.aggregates:AggregateMixin"),
                Attributes("ninja_devx.crud.transfer:ExportMixin"),
                Attributes("ninja_devx.crud.transfer:ImportMixin"),
                Attributes("ninja_devx.crud.sharing:ObjectSharingMixin"),
                Attributes("ninja_devx.crud.soft_delete:SoftDeleteMixin"),
                Attributes("ninja_devx.crud.soft_delete:SoftDelete"),
                Signature("ninja_devx.crud.soft_delete:soft_delete_unique"),
                Text(
                    """
                    ### Model bases (`ninja_devx.models`)

                    Abstract models for bookkeeping columns; controllers fill the user columns.

                    | Base | Columns | Notes |
                    |---|---|---|
                    | `TimeStamped` | `created_at`, `updated_at` | `auto_now_add`/`auto_now`; `created_at` is indexed |
                    | `UserStamped` | `created_by`, `updated_by` | nullable `AUTH_USER_MODEL` keys (`SET_NULL`), set from the request user on create and update |
                    | `Stamped` | all of the above | |
                    | `SoftDeletable` | `deleted_at`, `deleted_by` | the defaults `SoftDeleteMixin` uses without a `soft_delete` configuration |

                    Every column is `editable=False` and is left out of generated input schemas.
                    """
                ),
                Attributes("ninja_devx.crud.nested:Parent"),
                Attributes("ninja_devx.http.conditional:ETag"),
                Classes(
                    "Search backends",
                    [
                        "ninja_devx.crud.search:IContainsSearch",
                        "ninja_devx.crud.search:PostgresSearch",
                    ],
                ),
                Text(
                    """
                    ### `LimitOffsetPagination`

                    `pagination_class = LimitOffsetPagination` with `pagination_options`:

                    | Option | Type | Default | Description |
                    |---|---|---|---|
                    | `limit` | `int` | `100` | page size when the client sends no `?limit=` |
                    | `max_limit` | `int` | `1000` | upper bound for `?limit=` |
                    | `count` | `bool \\| Literal["estimate"] \\| int` | `True` | `True`: exact `COUNT(*)`. `False`: no count query, `null`, one extra row fetched instead. `"estimate"`: `pg_class.reltuples` on PostgreSQL for an unfiltered queryset, exact otherwise. `N`: exact up to `N` rows, then `N` with `X-Total-Count: N+` |
                    | `max_offset` | `int \\| None` | `None` | reject deeper `?offset=` with 422 |

                    Query parameters: `limit`, `offset`. The response is
                    `{"items", "count", "next", "previous"}` with absolute links that keep the
                    other query parameters.

                    ### `CursorPagination`

                    `pagination_class = CursorPagination` with `pagination_options`:

                    | Option | Type | Default | Description |
                    |---|---|---|---|
                    | `page_size` | `int` | `NINJA_PAGINATION_PER_PAGE` | items per page |
                    | `max_page_size` | `int` | `NINJA_PAGINATION_MAX_PER_PAGE_SIZE` | upper bound for `?page_size=` |

                    Query parameters: `cursor`, `page_size`. Ordering comes from the request
                    (`ordering_param`), `default_ordering`, `Meta.ordering`, then `-pk`.

                    ### Parameter annotations

                    | Annotation | Resolves to | Exposed in OpenAPI |
                    |---|---|---|
                    | `Lookup` | the lookup value, typed like `lookup_field` | path `{lookup_param}` |
                    | `Instance[Model]` | the object (404, object permissions) | path `{lookup_param}` |
                    | `Locked[Model]` | the object with `select_for_update()` | path `{lookup_param}` |
                    | `Filters` | the filter schema (generated or `filter_schema`) | query parameters |
                    | `Ordering` | the ordering schema | query `ordering_param` |
                    | `Patch[In]` | `PatchData` of the fields sent | body |
                    | `Annotated[int \\| Out, Expandable()]` (output field) | the key, or `Out` with `?expand=` | query `expand_param` |
                    | `BulkPatch[In]` / `BulkDelete` | `{"pks": [...], "data": {...}}` / `{"pks": [...]}` | body |
                    """
                ),
            ],
        ),
        Page(
            "permissions",
            "Permissions and visibility",
            """
            Built-in permissions, their arguments, and field visibility.
            See the [Permissions guide](../guide/permissions.md) and
            [Field visibility](../guide/visibility.md).
            """,
            [
                Attributes("ninja_devx.security.permissions:BasePermission"),
                Classes(
                    "Built-in permissions",
                    [
                        f"ninja_devx.security.permissions:{name}"
                        for name in (
                            "AllowAny",
                            "DenyAll",
                            "IsAuthenticated",
                            "IsAuthenticatedOrReadOnly",
                            "IsReadOnly",
                            "IsStaff",
                            "IsSuperuser",
                            "HasDjangoPermission",
                            "DjangoModelPermissions",
                            "IsOwner",
                            "Also",
                        )
                    ],
                ),
                Signature("ninja_devx.security.permissions:as_permission"),
                Attributes("ninja_devx.security.object_permissions:ObjectPermissions"),
                Classes(
                    "Object permission backends",
                    [
                        "ninja_devx.contrib.grants.backends:GrantsBackend",
                        "ninja_devx.security.object_permissions:GuardianBackend",
                        "ninja_devx.security.object_permissions:DjangoBackend",
                    ],
                ),
                *(
                    Signature(f"ninja_devx.security.object_permissions:{name}")
                    for name in (
                        "assign_perm",
                        "remove_perm",
                        "grants_for",
                        "get_perms",
                        "get_objects_for_user",
                        "get_backend",
                    )
                ),
                Signature("ninja_devx.serialization.visibility:VisibleTo"),
                Signature("ninja_devx.serialization.visibility:WriteVisibleTo"),
                Attributes("ninja_devx.serialization.visibility:Expandable"),
                Text(
                    """
                    ### `Sensitive`

                    Field metadata: `Annotated[str, Sensitive()]`. Carries no configuration;
                    masked by `ExportMixin`, `mask_validation_input` and `AuditPrivacy`. See
                    [Operations](../guide/operations.md#sensitive-fields).
                    """
                ),
                Signature("ninja_devx.serialization.privacy:sensitive_fields"),
                Signature("ninja_devx.serialization.privacy:mask"),
                Signature("ninja_devx.serialization.privacy:redact_payload"),
            ],
        ),
        Page(
            "dependency-injection",
            "Dependency injection",
            """
            The built-in container, parameter injection and the adapters.
            See the [Dependency injection guide](../guide/dependency-injection.md).
            """,
            [
                *(
                    Signature(
                        f"ninja_devx.dependencies.container:Container.{name}",
                        display=f"Container.{name}",
                    )
                    for name in (
                        "singleton",
                        "scoped",
                        "transient",
                        "register",
                        "instance",
                        "override",
                        "resolve",
                        "aresolve",
                        "scope",
                        "check",
                        "close",
                        "aclose",
                    )
                ),
                Text(
                    """
                    ### Parameter injection

                    | Annotation | Value |
                    |---|---|
                    | `Inject[T]` | `T` resolved from the controller's container for this call |
                    | `Annotated[T, Resolve(fn)]` | `fn(request)` (sync, or `async def` in async operations) |
                    """
                ),
                Signature("ninja_devx.security.auth:request_context"),
                Signature("ninja_devx.security.auth:authenticated_user"),
                Attributes("ninja_devx.contrib.dishka:DishkaResolver"),
                Signature("ninja_devx.contrib.dishka:provide_controllers"),
            ],
        ),
        Page(
            "http",
            "Tenancy, caching, throttling and idempotency",
            """
            See [Multi-tenancy](../guide/tenancy.md), [HTTP caching](../guide/conditional.md),
            [Throttling](../guide/throttling.md) and [Hooks and idempotency](../guide/hooks.md).
            """,
            [
                Signature("ninja_devx.security.tenancy:current_tenant"),
                Signature("ninja_devx.http.conditional:conditional"),
                Classes(
                    "Throttles",
                    [
                        f"ninja_devx.http.throttling:{name}"
                        for name in (
                            "RateThrottle",
                            "UserRateThrottle",
                            "AnonRateThrottle",
                            "ClientRateThrottle",
                            "ScopedRateThrottle",
                            "TenantRateThrottle",
                        )
                    ],
                ),
                Signature("ninja_devx.http.throttling:parse_rate"),
                Classes(
                    "Throttle storage (`RateThrottle(storage=...)`, `NINJA_DEVX['THROTTLE_STORAGE']`)",
                    [
                        "ninja_devx.http.throttling:ThrottleStorage",
                        "ninja_devx.http.throttling:CacheThrottleStorage",
                    ],
                ),
                Signature("ninja_devx.idempotency.policy:idempotent"),
            ],
        ),
        Page(
            "middleware",
            "Middleware, health and rendering",
            """
            Router and API middleware, health endpoints, fast JSON renderers and OpenTelemetry.
            See [Middleware and operations](../guide/middleware.md).
            """,
            [
                Signature("ninja_devx.http.middleware:use_middleware"),
                Signature("ninja_devx.http.middleware:middleware_decorator"),
                Attributes("ninja_devx.http.middleware:RequestIDMiddleware"),
                Signature("ninja_devx.http.middleware:get_request_id"),
                Attributes("ninja_devx.http.middleware:DeprecationMiddleware"),
                Classes(
                    "Other middleware",
                    [
                        "ninja_devx.http.middleware:ServerTimingMiddleware",
                        "ninja_devx.http.middleware:RateLimitHeadersMiddleware",
                        "ninja_devx.http.security:SecurityHeadersMiddleware",
                        "ninja_devx.http.cache:ResponseCacheMiddleware",
                        "ninja_devx.http.hardening:MaxBodySizeMiddleware",
                        "ninja_devx.http.hardening:EnforceContentTypeMiddleware",
                        "ninja_devx.http.hardening:JsonDepthMiddleware",
                        "ninja_devx.http.pagination_headers:PaginationHeadersMiddleware",
                        "ninja_devx.contrib.otel:OpenTelemetryMetricsMiddleware",
                    ],
                ),
                Signature("ninja_devx.http.cache:invalidate_cache"),
                Signature("ninja_devx.http.middleware:record_rate_limit"),
                Signature(
                    "ninja_devx.http.explain:QueryExplainMiddleware",
                    display="QueryExplainMiddleware",
                ),
                Attributes("ninja_devx.http.versioning:VersionedResponseMixin"),
                Signature(
                    "ninja_devx.http.versioning:VersionedResponseMiddleware",
                    display="VersionedResponseMiddleware",
                ),
                Attributes("ninja_devx.http.requestlog:RequestLogMiddleware"),
                Attributes("ninja_devx.http.requestlog:RequestLogPlugin"),
                Signature("ninja_devx.http.requestlog:register_api_key_reader"),
                Classes("Log formatting", ["ninja_devx.http.requestlog:JSONFormatter"]),
                Attributes("ninja_devx.http.health:HealthController"),
                Classes(
                    "Health checks",
                    [
                        f"ninja_devx.http.health:{name}"
                        for name in ("DatabaseCheck", "CacheCheck", "MigrationsCheck")
                    ],
                ),
                Attributes("ninja_devx.serialization.renderers:ORJSONRenderer"),
                Classes("Other renderers", ["ninja_devx.serialization.renderers:MsgspecRenderer"]),
                Attributes("ninja_devx.contrib.otel:OpenTelemetryHook"),
            ],
        ),
        Page(
            "contrib",
            "API keys, audit log, webhooks, uploads and jobs",
            """
            The optional Django apps and adapters in `ninja_devx.contrib`. The apps
            (`apikeys`, `audit`, `webhooks`, `uploads`, `jobs`) need `INSTALLED_APPS` and a
            migration; `redis_throttle` and `nplusone` are adapters with no app of their own.
            See [API keys](../guide/api-keys.md), [Audit log](../guide/audit.md),
            [Webhooks](../guide/webhooks.md), [Uploads](../guide/uploads.md),
            [Jobs](../guide/jobs.md), [Operations](../guide/operations.md) and
            [N+1 detection and devx_doctor](../guide/doctor.md).
            """,
            [
                Text("## API keys (`ninja_devx.contrib.apikeys`)"),
                Signature("ninja_devx.contrib.apikeys.auth:create_api_key"),
                Signature("ninja_devx.contrib.apikeys.auth:revoke_api_key"),
                Classes(
                    "Authentication and scopes",
                    [
                        f"ninja_devx.contrib.apikeys.auth:{name}"
                        for name in (
                            "APIKeyAuth",
                            "APIKeyBearer",
                            "RequiresScope",
                            "HasScopes",
                            "APIKeyRateThrottle",
                        )
                    ],
                ),
                Signature("ninja_devx.contrib.apikeys.auth:scope_allows"),
                Attributes("ninja_devx.contrib.apikeys.api:APIKeyController"),
                Text("## Audit log (`ninja_devx.contrib.audit`)"),
                Attributes("ninja_devx.contrib.audit.log:AuditMixin"),
                Attributes("ninja_devx.contrib.audit.privacy:AuditPrivacy"),
                Signature("ninja_devx.contrib.audit.log:record"),
                Signature("ninja_devx.contrib.audit.log:snapshot"),
                Signature("ninja_devx.contrib.audit.log:diff"),
                Signature("ninja_devx.contrib.audit.log:redact"),
                Attributes("ninja_devx.contrib.audit.api:AuditFilters"),
                Text("## Webhooks (`ninja_devx.contrib.webhooks`)"),
                Signature("ninja_devx.contrib.webhooks.outbox:publish"),
                Signature("ninja_devx.contrib.webhooks.outbox:deliver_due"),
                Signature("ninja_devx.contrib.webhooks.outbox:deliver_event"),
                Signature("ninja_devx.contrib.webhooks.outbox:event_matches"),
                Signature("ninja_devx.contrib.webhooks.signing:verify_signature"),
                Signature("ninja_devx.contrib.webhooks.signing:signature_headers"),
                Signature("ninja_devx.contrib.webhooks.signing:generate_secret"),
                Attributes("ninja_devx.contrib.webhooks.network:URLPolicy"),
                Signature("ninja_devx.contrib.webhooks.network:check_url"),
                Attributes("ninja_devx.contrib.webhooks.network:SafeHTTPTransport"),
                *(
                    Signature(f"ninja_devx.contrib.webhooks.secrets:{name}")
                    for name in ("encrypt_secret", "decrypt_secret", "reencrypt_secret")
                ),
                Attributes("ninja_devx.contrib.webhooks.api:WebhookEndpointController"),
                Text("## Uploads (`ninja_devx.contrib.uploads`)"),
                Attributes("ninja_devx.contrib.uploads.api:UploadController"),
                Attributes("ninja_devx.contrib.uploads.api:UploadPolicy"),
                Attributes("ninja_devx.contrib.uploads.backends:S3Signer"),
                Classes("Test signer", ["ninja_devx.contrib.uploads.backends:FakeSigner"]),
                Signature("ninja_devx.contrib.uploads.api:safe_filename"),
                Text("## Jobs (`ninja_devx.contrib.jobs`)"),
                Text(
                    """
                    `JobsController`: `GET /` (the caller's jobs, paginated), `GET /{id}` and
                    `POST /{id}/cancel`. Mount next to the endpoints that call `start_job`.
                    Maintain with `manage.py devx_jobs prune`/`retry` (see
                    [Commands](commands.md)).
                    """
                ),
                Attributes("ninja_devx.contrib.jobs.api:JobOut"),
                Signature("ninja_devx.contrib.jobs.runner:start_job"),
                Signature("ninja_devx.contrib.jobs.runner:run_job"),
                Signature("ninja_devx.contrib.jobs.runner:accepted"),
                Signature("ninja_devx.contrib.jobs.runner:job"),
                Signature("ninja_devx.contrib.jobs.runner:resolve_job"),
                Signature("ninja_devx.contrib.jobs.runner:JobContext", display="JobContext"),
                Text("## Redis throttle storage (`ninja_devx.contrib.redis_throttle`)"),
                Classes(
                    "Throttle storage", ["ninja_devx.contrib.redis_throttle:RedisThrottleStorage"]
                ),
                Text("## N+1 detection (`ninja_devx.contrib.nplusone`)"),
                Text(
                    """
                    An adapter over [django-zeal](https://github.com/taobojlen/django-zeal)
                    (the `zeal` extra): add `NPlusOnePlugin()`/`NPlusOneMiddleware()` so every
                    request runs inside zeal's tracking context, and its errors are rewritten
                    to name the controller and the fix. A no-op when `django-zeal` is not
                    installed.
                    """
                ),
                Classes(
                    "N+1 middleware",
                    [
                        "ninja_devx.contrib.nplusone:NPlusOneMiddleware",
                        "ninja_devx.contrib.nplusone:NPlusOnePlugin",
                    ],
                ),
                Signature("ninja_devx.contrib.nplusone:explain_n_plus_one"),
                Signature("ninja_devx.contrib.nplusone:zeal_installed"),
                Signature("ninja_devx.contrib.nplusone:zeal_strict"),
                Text("## Task queue adapters (`ninja_devx.contrib.tasks`)"),
                Classes(
                    "Task queues",
                    [
                        f"ninja_devx.contrib.tasks:{name}"
                        for name in (
                            "CeleryTaskQueue",
                            "DramatiqTaskQueue",
                            "RQTaskQueue",
                            "TaskiqTaskQueue",
                            "TemporalTaskQueue",
                            "FastStreamTaskQueue",
                            "FrameworkTaskQueue",
                            "DeferredTaskQueue",
                        )
                    ],
                ),
            ],
        ),
        Page(
            "errors",
            "Errors",
            """
            Error rules, built-in domain errors and the package's exceptions.
            See the [Errors guide](../guide/errors.md).
            """,
            [
                Signature("ninja_devx.http.errors:ErrorMap.map", display="ErrorMap.map"),
                Signature("ninja_devx.http.errors:mask_validation_input"),
                Signature("ninja_devx.layers.errors:DomainError"),
                Runtime(domain_errors),
                Runtime(exceptions_and_warnings),
            ],
        ),
        Page(
            "settings",
            "Settings",
            """
            Every key of `settings.NINJA_DEVX`. Class attributes on your controllers override
            them; unknown keys raise `ImproperlyConfigured`. See the [Settings guide](../guide/settings.md).
            """,
            [
                Attributes(
                    "ninja_devx.configuration.settings:NinjaDevXSettings",
                    title="`NINJA_DEVX`",
                    defaults=_settings_default,
                ),
            ],
        ),
        Page(
            "testing",
            "Testing",
            """
            The pytest plugin (loaded automatically) and `ninja_devx.testing.clients`.
            See the [Testing guide](../guide/testing.md).
            """,
            [
                Runtime(pytest_plugin),
                *(
                    Signature(f"ninja_devx.testing.clients:{name}")
                    for name in (
                        "client_for",
                        "async_client_for",
                        "assert_max_queries",
                        "assert_max_hops",
                        "capture_commits",
                    )
                ),
                Signature("ninja_devx.testing.contracts:contract_schema"),
                Signature("ninja_devx.layers.testing:make_context"),
                Signature("ninja_devx.testing.factories:sample"),
                Signature("ninja_devx.testing.factories:samples"),
            ],
        ),
        Page(
            "commands",
            "Commands and checks",
            """
            Management commands, the unasync tool and system checks.
            See [Code generation](../guide/codegen.md) and [System checks](../guide/checks.md).
            """,
            [
                Runtime(management_command("devx_scaffold")),
                Runtime(management_command("devx_openapi")),
                Runtime(management_command("devx_inspect")),
                Runtime(management_command("devx_doctor")),
                Runtime(management_command("devx_uploads")),
                Runtime(template_command("devx_startapp", "startapp")),
                Runtime(template_command("devx_startproject", "startproject")),
                Runtime(management_command("devx_apikey", "ninja_devx.contrib.apikeys")),
                Runtime(management_command("devx_webhooks", "ninja_devx.contrib.webhooks")),
                Runtime(management_command("devx_jobs", "ninja_devx.contrib.jobs")),
                Runtime(unasync_cli),
                Runtime(system_checks),
            ],
        ),
    ]


def render_all() -> dict[Path, str]:
    rendered = {OUTPUT / f"{page.slug}.md": page.render() for page in pages()}
    metadata = tomllib.loads((ROOT / "pyproject.toml").read_text())["project"]
    classifiers = metadata["classifiers"]
    python_versions = [
        item.rsplit(" :: ", 1)[1]
        for item in classifiers
        if re.fullmatch(r"Programming Language :: Python :: \d+\.\d+", item)
    ]
    django_versions = [
        item.rsplit(" :: ", 1)[1]
        for item in classifiers
        if re.fullmatch(r"Framework :: Django :: \d+\.\d+", item)
    ]
    ninja = next(item for item in metadata["dependencies"] if item.startswith("django-ninja"))
    table = (
        "<!-- support-matrix:start -->\n"
        "| Component | Declared compatibility |\n|---|---|\n"
        f"| Python | {', '.join(python_versions)} |\n"
        f"| Django | {', '.join(django_versions)} |\n"
        f"| django-ninja | `{ninja}` |\n"
        "<!-- support-matrix:end -->"
    )
    support = ROOT / "docs" / "project" / "support.md"
    rendered[support] = re.sub(
        r"<!-- support-matrix:start -->.*?<!-- support-matrix:end -->",
        lambda match: table,
        support.read_text(),
        flags=re.DOTALL,
    )
    return rendered


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args(list(argv) if argv is not None else None)
    sys.path[:0] = [str(SOURCE), str(ROOT)]
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "tests.settings")
    import django

    django.setup()
    rendered = render_all()
    outdated = [
        path
        for path, content in rendered.items()
        if not path.exists() or path.read_text() != content
    ]
    if arguments.check:
        for path in outdated:
            print(f"outdated: {path.relative_to(ROOT)}", file=sys.stderr)
        return 1 if outdated else 0
    OUTPUT.mkdir(parents=True, exist_ok=True)
    for path in outdated:
        path.write_text(rendered[path])
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
